### ISSUE TITLE
workspace_client overflow for req.url set to empty string is confusing

### ISSUE THREAD

**Issue by nigoroll** [varnishcache/varnish-cache#2012] opened 2016-07-11 09:06 UTC
The behavior exposed by this simple vtc is confusing: The error message reports a WS overflow while in fact the root case is setting `req.url` to an empty value. In a real-world VCL cause and effect are likely to be spread out.
```
varnishtest "Confusing workspace_client overflow for req.url unset"

server s1 {
} -start

varnish v1 -vcl+backend {
	sub vcl_recv {
	    return (synth(200));
	}
	sub vcl_hash {
	    set req.url = req.http.empty;
	}
} -start

client c1 {
	txreq -url /foo
	rxresp
	expect resp.status == 200
} -run
```
gives:
```
**** v1    0.4 vsl|       1001 ReqMethod       c GET
**** v1    0.4 vsl|       1001 ReqURL          c /foo
**** v1    0.4 vsl|       1001 ReqProtocol     c HTTP/1.1
**** v1    0.4 vsl|       1001 ReqHeader       c X-Forwarded-For: 127.0.0.1
**** v1    0.4 vsl|       1001 VCL_call        c RECV
**** v1    0.4 vsl|       1001 VCL_return      c synth
**** v1    0.4 vsl|       1001 VCL_call        c HASH
**** v1    0.4 vsl|       1001 LostHeader      c req.url
**** v1    0.4 vsl|       1001 VCL_return      c lookup
**** v1    0.4 vsl|       1001 Timestamp       c Process: 1468227572.222241 0.000026 0.000026
**** v1    0.4 vsl|       1001 RespHeader      c Date: Mon, 11 Jul 2016 08:59:32 GMT
**** v1    0.4 vsl|       1001 RespHeader      c Server: Varnish
**** v1    0.4 vsl|       1001 RespHeader      c X-Varnish: 1001
**** v1    0.4 vsl|       1001 RespProtocol    c HTTP/1.1
**** v1    0.4 vsl|       1001 RespStatus      c 200
**** v1    0.4 vsl|       1001 RespReason      c OK
**** v1    0.4 vsl|       1001 RespReason      c OK
**** v1    0.4 vsl|       1001 VCL_call        c SYNTH
**** v1    0.4 vsl|       1001 RespHeader      c Content-Type: text/html; charset=utf-8
**** v1    0.4 vsl|       1001 RespHeader      c Retry-After: 5
**** v1    0.4 vsl|       1001 VCL_return      c deliver
**** v1    0.4 vsl|       1001 RespHeader      c Content-Length: 213
**** v1    0.4 vsl|       1001 Storage         c malloc Transient
**** v1    0.4 vsl|       1001 RespHeader      c Accept-Ranges: bytes
**** v1    0.4 vsl|       1001 Debug           c RES_MODE 2
**** v1    0.4 vsl|       1001 RespHeader      c Connection: keep-alive
**** v1    0.4 vsl|       1001 Error           c workspace_client overflow
**** v1    0.4 vsl|       1001 RespProtocol    c HTTP/1.1
**** v1    0.4 vsl|       1001 RespStatus      c 500
**** v1    0.4 vsl|       1001 RespReason      c Internal Server Error
**** v1    0.4 vsl|       1001 Timestamp       c Resp: 1468227572.222347 0.000132 0.000106
**** v1    0.4 vsl|       1001 ReqAcct         c 21 0 21 0 0 0
**** v1    0.4 vsl|       1001 End             c 
**** v1    0.4 vsl|       1000 SessClose       c TX_EOF 0.000
**** v1    0.4 vsl|       1000 End             c 
```

The cause is that in `vrt_do_string()` we mark a workspace overflow when `VRT_String()` returns `NULL` or the empty string.

**Comment by nigoroll** [comment] 2016-07-11 09:37
At the moment we're using the "ws overlow" error mechanism also for the "header set to null" case and the question is if/how we want to differentiate between the two cases. We can easily fall back to "just log the losthdr" with
```
diff --git a/bin/varnishd/cache/cache_vrt_var.c b/bin/varnishd/cache/cache_vrt_var.c
index 0667bde..bd2c828 100644
--- a/bin/varnishd/cache/cache_vrt_var.c
+++ b/bin/varnishd/cache/cache_vrt_var.c
@@ -55,7 +55,8 @@ vrt_do_string(const struct http *hp, int fld,
        b = VRT_String(hp->ws, NULL, p, ap);
        if (b == NULL || *b == '\0') {
                VSLb(hp->vsl, SLT_LostHeader, "%s", err);
-               WS_MarkOverflow(hp->ws);
+               if (b == NULL)
+                       WS_MarkOverflow(hp->ws);
                return;
        }
        http_SetH(hp, fld, b);
```
This this change we'd just issue the `SLT_LostHeader` and otherwise the set statement would have no effect - but is this what we want?

**Comment by fgsch** [comment] 2016-07-11 09:38
Duplicate of #1856

**Closed by fgsch** 2016-07-11 09:38 UTC

**Comment by hermunn** [comment] 2016-08-03 15:17
Backport review: Nothing commited, nothing to backport.

However, there seems to be good reason to react to #1895 soon, so that we might get to close #1856.
