### ISSUE TITLE
net::ERR_CONNECTION_CLOSED on Chrome 69

### ISSUE THREAD

**Issue by CarloCannas** [varnishcache/varnish-cache#2775] opened 2018-09-13 23:29 UTC
Some resources requested on h2 may fail to load with error net::ERR_CONNECTION_CLOSED using Chrome 69.

I received yesterday the latest Chrome upgrade (Chrome 69) and I started noticing some missing images on a website that uses Varnish with HTTP/2 enabled. The problem is not always reproducible: it may load everything fine without errors, but on some pages the error shows up after a few reloads.
I was able to reproduce it only on Chrome 69, previous Chrome versions or Firefox seems unable to trigger the bug.
I dumped the HTTP/2 traffic between the browser and Varnish: it showed a PRIORITY frame from Chrome, followed immediately by a GOAWAY from Varnish and the closing of the TCP stream.
The PRIORITY frame was sent to a stream just closed.
That's exactly the problem: Varnish doesn't accept PRIORITY frames on a closed stream and treats them as a protocol violation.
This is however not a protocol violation: [rfc7540,l,1130,1131](https://tools.ietf.org/html/rfc7540#page-21) states that

> PRIORITY can be sent and received in any stream state

[bin/varnishd/http2/cache_http2_proto.c:L928](https://github.com/varnishcache/varnish-cache/blob/6fdc89c1fdd12bb83fadd8412faa1d7703761e36/bin/varnishd/http2/cache_http2_proto.c#L928) is the culprit: that return ultimately triggers the GOAWAY, this codepath is reached whenever a PRIORITY frame is received and the corresponding stream doesn't appear in h2->streams.

A minimal testcase which shows the issue:

```
varnishtest "PRIORITY on closed stream"

server s1 {
	rxreq
	txresp
}

varnish v1 -vcl+backend {} -start

varnish v1 -cliok "param.set feature +http2"
varnish v1 -cliok "param.set debug +syncvsl"

client c1 {
	stream 1 {
		txreq
		rxresp

		delay .1

		txprio
	} -run
	stream 3 {
		txreq
		rxresp
	} -run
} -run
```

**Comment by dugwood** [comment] 2018-09-24 10:53
Seems that 6.0.1 and 6.1.0 are both affected. I've tried to find out if other «big» websites are impacted, for example https://www.fastly.com/customers and can't reproduce.

Perhaps they're still using 5.2 release? Hum, no, just tested 5.2.1 and it's buggy too.

Any plans to release this shortly?

Thanks for the patch!

**Comment by CarloCannas** [comment] 2018-09-24 11:52
[I read](https://docs.fastly.com/guides/vcl-tutorials/guide-to-vcl) that they use a custom version of Varnish 2.1, so their HTTP2 is probably not provided by Varnish.
I too tried to find a big website affected, but it looks like they use something else to do the HTTP2 termination.
My patch is still work in progress, but a pull request should arrive soon.

**Comment by fgsch** [comment] 2018-09-24 23:05
@dugwood fastly http/2 is based on h2o.

**Comment by dugwood** [comment] 2018-10-04 15:00
@CarloCannas thanks for all your work on this bug. Do you think it will be available as a bugfix release when all checks are passed? Or will we need to wait until March for this to be fixed (2 releases a year schedule)?

So far disabling H2 was the only viable option (Chrome 69 is used by more than 25% of all my clients' visitors).

**Comment by CarloCannas** [comment] 2018-10-04 16:12
@dugwood I'm sorry, but I have no idea. I was planning to ask the maintainers the same thing once the code was merged.

@bsdphk, @Dridi, @daghf: are you going to do a new release in the near future which includes this fix?

We did the same thing on our Varnish instances: we disabled HTTP2 and currently waiting to have an idea of when the release which fixes this will be available.

**Comment by Dridi** [comment] 2018-10-04 17:49
Yes, 6.0 is the new LTS release so you should expect at the very least a 6.0.2 ideally after this patch is merged and back-ported. Getting the latest h2 fixes in 6.0.2 is our goal.

**Closed** 2018-10-05 08:49 UTC

**Comment by ingvarha** [comment] 2018-10-29 13:50
I tried backporting this to 6.0.1 with a bit strange results. My attempt on the backport here: https://paste.fedoraproject.org/paste/1ZOgLI4bAvY4s~0GrMT4-Q

When I build with this, make check fails on tests/r02387.vtc and tests/t02003.vtc :

r02387.log:  https://paste.fedoraproject.org/paste/afgnxYpsjnmUv~oRp44ZgQ
t02003.log: https://paste.fedoraproject.org/paste/JfqRfKgzkbEZnPyPU2SE2w

But if I run the test by hand afterwards, they succeed:

./varnishtest tests/r02387.vtc -v : https://paste.fedoraproject.org/paste/7xKNZymzZnGmdxHAuFsMaw
./varnishtest tests/t02003.vtc -v :  https://paste.fedoraproject.org/paste/nOrRyBZ9YXaJ~zwR76PluA

Am I missing something?

Ingvar

**Comment by CarloCannas** [comment] 2018-10-29 15:31
@ingvarha it looks like you only applied the last commit of the [pull request](https://github.com/varnishcache/varnish-cache/pull/2781), you should apply all three. Please note however that a [new 6.0.2 release is going to be released](https://github.com/varnishcache/varnish-cache/pull/2802), which includes this fix.

**Comment by Dridi** [comment] 2018-10-30 09:59
@ingvarha, please give a try to #2802, it is meant to include any bug fix or new feature that doesn't touch the ABIs we care about (VMODs and `libvarnishapi` consumers).
