### ISSUE TITLE
libvcc: max symbol size assertion

### ISSUE THREAD

**Issue by JonathanHuot** [varnishcache/varnish-cache#2336] opened 2017-05-29 07:10 UTC
## Expected Behavior
When using long symbol names in VCL, either varnishtest and varnishd starts; or refuses to start but output a meaningful message about the VCL error.

## Current Behavior
Assert in VCC-compiler : 
```
**** v1    0.2 CLI RX|Message from VCC-compiler:
**** v1    0.2 CLI RX|Assert error in vcc_ParseNew(), vcc_vmod.c line 315:
**** v1    0.2 CLI RX|  Condition(snprintf(buf1, sizeof buf1, ", &vo_%s, \"%s\"", sy1->name, sy1->name) < sizeof buf1) not true.
**** v1    0.2 CLI RX|Running VCC-compiler failed, signal 6, core dumped
**** v1    0.2 CLI RX|VCL compilation failed
```

## Possible Solution
I suggest to explain what is failing (size of symbol exceed) and which symbol (pool_foobar_(..)). I got this error in a config with thousand of VCL lines and I had to add debug information in libvcc to progress.

## Steps to Reproduce (for bugs)

1. Run varnishtest with :
```
varnishtest "Max symbol name"

varnish v1 -vcl {
        import directors;
        backend foobar {
                .host = "127.0.0.1";
        }
        sub vcl_init {
                new pool_foobar_foobar_foobar_foobar_foobar_foobar_foobar_foobar = directors.round_robin();
                pool_foobar_foobar_foobar_foobar_foobar_foobar_foobar_foobar.add_backend(foobar);
        }
        sub vcl_recv {
                set req.backend_hint = pool_foobar_foobar_foobar_foobar_foobar_foobar_foobar_foobar;
        }
} -start
```
## Context
We're generating configuration from 3rd-party identifiers which can be longer than the maximum size of symbol.

## Your Environment

* Version used: 4.1.7, 5.1.2, master@d87b58e

**Comment by Dridi** [comment] 2017-05-29 07:24
Duplicate of #2157, being currently worked on in the master branch, unlikely to be back-ported because this is a huge breaking change.

See "Statistics" in the description of https://github.com/varnishcache/varnish-cache/issues/2318#issue-223798175.

**Closed by Dridi** 2017-05-29 07:24 UTC
