### ISSUE TITLE
Varnish returns 503 (Uncached req.body can only be consumed once.) when restarting POST.

### ISSUE THREAD

**Issue by wizkids** [varnishcache/varnish-cache#1943] opened 2016-05-09 16:10 UTC
I am currently trying to add an extra header to a request, before forwarding it to the backend. I do this by:

1. Modifying the original request (Host and URL).
2. Adding the header from the backend response to the request.
3. Restarting the request.

Works fine for GET requests but for POST requests I get a 503 Backend fetch failed with VCL_Error = Uncached req.body can only be consumed once.

I know that Varnish is not supposed to cache POST requests, but due to easier backend implementation I would like to add this header regardless of POST or GET request.

## Steps to Reproduce
/etc/varnish/default.vcl (I've altered it to provide the shortest amount of VCL that reproduces the error):

    backend default {
        .host = "127.0.0.1";
        .port = "80";
    }

    sub vcl_recv {
        if (req.restarts == 0){
            set req.url = req.url + "/test"; // Added for test purposes
            set req.http.Host = "session.example.com";
            return(hash);
        }
    
        set req.url = req.url + "/test2"; // Added for test purposes
        set req.http.Host = "service.example.com";
        return(pass);
    }
    
    sub vcl_deliver {
        if (req.restarts == 0){
            set req.http.X-Logged-In = resp.http.X-Logged-In;
            return(restart);
        }
    }

I am testing by sending a POST request from another LAMP server using `file_get_contents()`:

    $opts = array('http' =>
        array(
            'method'  => 'POST',
            'content' => http_build_query(array(
              "param1" => "value1",
              "param2" => "value2",
            ))
        )
    );
    $result = file_get_contents("http://service.example.com", false, stream_context_create($opts));

Not sure if useful, but the value of `method` does not actually not affect the outcome. Only the value of `content` - if `content` is set the request fails, if not set the request completes successfully.

## Expected Behavior
I would assume that the response for GET and POST would be identical especially given that I modify both URL and host (I added those tests to see if that fixes the issue).

## Your Environment
- Varnish version: 4.0.2
- Operating System and version: Debian GNU/Linux 8.4 (jessie)

varnishlog excerpt for one request from the LAMP server:

        ====================================== varnishlog -g request
    *   << Request  >> 2         
    -   Begin          req 1 rxreq
    -   Timestamp      Start: 1462810070.962259 0.000000 0.000000
    -   Timestamp      Req: 1462810070.962259 0.000000 0.000000
    -   ReqStart       127.0.0.1 51081
    -   ReqMethod      POST
    -   ReqURL         /
    -   ReqProtocol    HTTP/1.0
    -   ReqHeader      Host: service.example.com:8082
    -   ReqHeader      Content-Length: 27
    -   ReqHeader      Content-Type: application/x-www-form-urlencoded
    -   ReqHeader      X-Forwarded-Proto: http
    -   ReqHeader      X-Forwarded-For: 10.1.2.235
    -   ReqUnset       X-Forwarded-For: 10.1.2.235
    -   ReqHeader      X-Forwarded-For: 10.1.2.235, 127.0.0.1
    -   VCL_call       RECV
    -   ReqURL         //test
    -   ReqUnset       Host: service.example.com:8082
    -   ReqHeader      Host: session.example.com
    -   VCL_return     hash
    -   VCL_call       HASH
    -   VCL_return     lookup
    -   Debug          "XXXX MISS"
    -   VCL_call       MISS
    -   VCL_return     fetch
    -   Link           bereq 3 fetch
    -   Timestamp      Fetch: 1462810070.969811 0.007552 0.007552
    -   Timestamp      ReqBody: 1462810070.969953 0.007694 0.000143
    -   RespProtocol   HTTP/1.1
    -   RespStatus     200
    -   RespReason     OK
    -   RespHeader     Date: Mon, 09 May 2016 16:07:50 GMT
    -   RespHeader     Server: Apache/2.4.10 (Debian)
    -   RespHeader     Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
    -   RespHeader     Set-Cookie: PHPSESSID=nto8lofefu77gnlvjucchv0d72; path=/
    -   RespHeader     Expires: Thu, 19 Nov 1981 08:52:00 GMT
    -   RespHeader     Pragma: no-cache
    -   RespHeader     Set-Cookie: MID=4b662e85-1920-4c95-ac66-5730b5d603c9; expires=Thu, 31-Dec-2099 23:00:00 GMT; Max-Age=2639631130; path=/; domain=example.com
    -   RespHeader     X-Logged-In: 0
    -   RespHeader     Content-Length: 7
    -   RespHeader     Content-Type: text/html; charset=UTF-8
    -   RespHeader     X-Varnish: 2
    -   RespHeader     Age: 0
    -   RespHeader     Via: 1.1 varnish-v4
    -   VCL_call       DELIVER
    -   ReqHeader      X-Logged-In: 0
    -   VCL_return     restart
    -   Timestamp      Process: 1462810070.969976 0.007717 0.000023
    -   Timestamp      Restart: 1462810070.969979 0.007720 0.000003
    -   Link           req 4 restart
    -   End            
    
    **  << BeReq    >> 3         
    --  Begin          bereq 2 fetch
    --  Timestamp      Start: 1462810070.962363 0.000000 0.000000
    --  BereqMethod    POST
    --  BereqURL       //test
    --  BereqProtocol  HTTP/1.0
    --  BereqHeader    Content-Type: application/x-www-form-urlencoded
    --  BereqHeader    X-Forwarded-Proto: http
    --  BereqHeader    X-Forwarded-For: 10.1.2.235, 127.0.0.1
    --  BereqHeader    Host: session.example.com
    --  BereqMethod    GET
    --  BereqProtocol  HTTP/1.1
    --  BereqHeader    Accept-Encoding: gzip
    --  BereqHeader    X-Varnish: 3
    --  VCL_call       BACKEND_FETCH
    --  VCL_return     fetch
    --  BackendOpen    17 default(127.0.0.1,,80) 127.0.0.1 54746 
    --  Backend        17 default default(127.0.0.1,,80)
    --  Timestamp      Bereq: 1462810070.962504 0.000140 0.000140
    --  Timestamp      Beresp: 1462810070.969562 0.007198 0.007058
    --  BerespProtocol HTTP/1.1
    --  BerespStatus   200
    --  BerespReason   OK
    --  BerespHeader   Date: Mon, 09 May 2016 16:07:50 GMT
    --  BerespHeader   Server: Apache/2.4.10 (Debian)
    --  BerespHeader   Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
    --  BerespHeader   Set-Cookie: PHPSESSID=nto8lofefu77gnlvjucchv0d72; path=/
    --  BerespHeader   Expires: Thu, 19 Nov 1981 08:52:00 GMT
    --  BerespHeader   Pragma: no-cache
    --  BerespHeader   Set-Cookie: MID=4b662e85-1920-4c95-ac66-5730b5d603c9; expires=Thu, 31-Dec-2099 23:00:00 GMT; Max-Age=2639631130; path=/; domain=example.com
    --  BerespHeader   X-Logged-In: 0
    --  BerespHeader   Content-Length: 7
    --  BerespHeader   Content-Type: text/html; charset=UTF-8
    --  TTL            RFC 0 -1 -1 1462810071 1462810071 1462810070 375007920 0
    --  VCL_call       BACKEND_RESPONSE
    --  TTL            VCL 120 10 0 1462810071
    --  VCL_return     deliver
    --  Storage        malloc Transient
    --  ObjProtocol    HTTP/1.1
    --  ObjStatus      200
    --  ObjReason      OK
    --  ObjHeader      Date: Mon, 09 May 2016 16:07:50 GMT
    --  ObjHeader      Server: Apache/2.4.10 (Debian)
    --  ObjHeader      Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
    --  ObjHeader      Set-Cookie: PHPSESSID=nto8lofefu77gnlvjucchv0d72; path=/
    --  ObjHeader      Expires: Thu, 19 Nov 1981 08:52:00 GMT
    --  ObjHeader      Pragma: no-cache
    --  ObjHeader      Set-Cookie: MID=4b662e85-1920-4c95-ac66-5730b5d603c9; expires=Thu, 31-Dec-2099 23:00:00 GMT; Max-Age=2639631130; path=/; domain=example.com
    --  ObjHeader      X-Logged-In: 0
    --  ObjHeader      Content-Length: 7
    --  ObjHeader      Content-Type: text/html; charset=UTF-8
    --  Fetch_Body     3 length stream
    --  BackendReuse   17 default(127.0.0.1,,80)
    --  Timestamp      BerespBody: 1462810070.969804 0.007441 0.000242
    --  Length         7
    --  BereqAcct      201 0 201 513 7 520
    --  End            
    
    *   << Request  >> 4         
    -   Begin          req 2 restart
    -   Timestamp      Start: 1462810070.969979 0.007720 0.000000
    -   ReqStart       127.0.0.1 51081
    -   ReqMethod      POST
    -   ReqURL         //test
    -   ReqProtocol    HTTP/1.0
    -   ReqHeader      Content-Length: 27
    -   ReqHeader      Content-Type: application/x-www-form-urlencoded
    -   ReqHeader      X-Forwarded-Proto: http
    -   ReqHeader      X-Forwarded-For: 10.1.2.235, 127.0.0.1
    -   ReqHeader      Host: session.example.com
    -   ReqHeader      X-Logged-In: 0
    -   VCL_call       RECV
    -   ReqURL         //test/test2
    -   ReqUnset       Host: session.example.com
    -   ReqHeader      Host: service.example.com
    -   VCL_return     pass
    -   VCL_call       HASH
    -   VCL_return     lookup
    -   VCL_call       PASS
    -   VCL_return     fetch
    -   Link           bereq 5 pass
    -   VCL_Error      Uncached req.body can only be consumed once.
    -   Timestamp      Fetch: 1462810070.970229 0.007971 0.000250
    -   RespProtocol   HTTP/1.1
    -   RespStatus     503
    -   RespReason     Backend fetch failed
    -   RespHeader     Date: Mon, 09 May 2016 16:07:50 GMT
    -   RespHeader     Server: Varnish
    -   RespHeader     Content-Type: text/html; charset=utf-8
    -   RespHeader     Retry-After: 5
    -   RespHeader     X-Varnish: 4
    -   RespHeader     Age: 0
    -   RespHeader     Via: 1.1 varnish-v4
    -   VCL_call       DELIVER
    -   VCL_return     deliver
    -   Timestamp      Process: 1462810070.970242 0.007983 0.000013
    -   RespHeader     Content-Length: 278
    -   Debug          "RES_MODE 2"
    -   RespHeader     Connection: close
    -   Timestamp      Resp: 1462810070.970293 0.008034 0.000051
    -   Debug          "XXX REF 1"
    -   ReqAcct        174 27 201 230 278 508
    -   End            
    
    **  << BeReq    >> 5         
    --  Begin          bereq 4 pass
    --  Timestamp      Start: 1462810070.970021 0.000000 0.000000
    --  BereqMethod    POST
    --  BereqURL       //test/test2
    --  BereqProtocol  HTTP/1.0
    --  BereqHeader    Content-Length: 27
    --  BereqHeader    Content-Type: application/x-www-form-urlencoded
    --  BereqHeader    X-Forwarded-Proto: http
    --  BereqHeader    X-Forwarded-For: 10.1.2.235, 127.0.0.1
    --  BereqHeader    X-Logged-In: 0
    --  BereqHeader    Host: service.example.com
    --  BereqHeader    X-Varnish: 5
    --  VCL_call       BACKEND_FETCH
    --  VCL_return     fetch
    --  Backend        17 default default(127.0.0.1,,80)
    --  FetchError     backend write error: 0 (Success)
    --  Timestamp      Bereq: 1462810070.970076 0.000055 0.000055
    --  BackendClose   17 default(127.0.0.1,,80)
    --  Timestamp      Beresp: 1462810070.970093 0.000072 0.000016
    --  Timestamp      Error: 1462810070.970095 0.000074 0.000003
    --  BerespProtocol HTTP/1.1
    --  BerespStatus   503
    --  BerespReason   Service Unavailable
    --  BerespReason   Backend fetch failed
    --  BerespHeader   Date: Mon, 09 May 2016 16:07:50 GMT
    --  BerespHeader   Server: Varnish
    --  VCL_call       BACKEND_ERROR
    --  BerespHeader   Content-Type: text/html; charset=utf-8
    --  BerespHeader   Retry-After: 5
    --  VCL_return     deliver
    --  Storage        malloc Transient
    --  ObjProtocol    HTTP/1.1
    --  ObjStatus      503
    --  ObjReason      Backend fetch failed
    --  ObjHeader      Date: Mon, 09 May 2016 16:07:50 GMT
    --  ObjHeader      Server: Varnish
    --  ObjHeader      Content-Type: text/html; charset=utf-8
    --  ObjHeader      Retry-After: 5
    --  Length         278
    --  BereqAcct      221 0 221 0 0 0
    --  End

**Comment by gquintard** [comment] 2016-05-11 08:41
Hi, it's not a bug (hence closing).

As varnish says, this is a VCL error, you tried to consume a request body twice without caching it, in other words, you brought it on yourself :-)

To avoid that, I'd recommend upgrading to 4.1 and using std.cache_req_body().
In 4.0, the function also exists, but it's flawed (https://www.varnish-cache.org/trac/ticket/1664), and so you'll have to use vmod-bodyaccess (https://github.com/aondio/libvmod-bodyaccess).

If more help is needed, please stop by IRC, or drop up a mail on varnish-misc.

**Closed by gquintard** 2016-05-11 08:41 UTC

**Comment by wizkids** [comment] 2016-05-11 08:44
Yeah, it was more of a "Why is this even supposed to generate an error" kind of thing. Cheers for the info!

**Comment by gquintard** [comment] 2016-05-11 08:46
Then, please, don't open bugs for this, rather, use the mailing-list.

**Comment by wizkids** [comment] 2016-05-11 08:51
It was in good faith as I didn't really understand _why_ it should generate an error (and while working as intended, I still don't), hence I interpreted it as a bug.

Will double check mailing list/IRC beforehand next time.

**Comment by gquintard** [comment] 2016-05-11 08:54
No problem really :-)

**Comment by hermunn** [comment] 2016-06-07 12:31
Backport review: Nothing committed, nothing to backport.
