### ISSUE TITLE
Assert error in smp_sml_getobj(), storage/storage_persistent_silo.c line 523

### ISSUE THREAD

**Issue by aksudha** [varnishcache/varnish-cache#2769] opened 2018-09-07 03:04 UTC
we are using varnish-6.0 and getting this panic frequently on prodution.
please help us to resolve this

Panic at: Fri, 07 Sep 2018 01:32:48 GMT
Assert error in smp_sml_getobj(), storage/storage_persistent_silo.c line 523:
  Condition((so->ptr) != 0) not true.
version = varnish-6.0 revision NOGIT, vrt api = 7.0
ident = Linux,3.10.0-693.11.6.el7.x86_64,x86_64,-junix,-spersistent,-spersistent,-spersistent,-spersistent,-spersistent,-spersistent,-sdefault,-hcritbit,epoll
now = 2968164.910878 (mono), 1536283877.027919 (real)
Backtrace:
  0x43b56b: /usr/sbin/varnishd() [0x43b56b]
  0x4a0fb2: /usr/sbin/varnishd(VAS_Fail+0x42) [0x4a0fb2]
  0x488e1e: /usr/sbin/varnishd() [0x488e1e]
  0x480f3c: /usr/sbin/varnishd() [0x480f3c]
  0x43a1a0: /usr/sbin/varnishd(ObjGetU32+0x20) [0x43a1a0]
  0x43a233: /usr/sbin/varnishd(ObjGetXID+0x23) [0x43a233]
  0x42831f: /usr/sbin/varnishd() [0x42831f]
  0x4594a7: /usr/sbin/varnishd() [0x4594a7]
  0x7fcedbe5de25: /lib64/libpthread.so.0(+0x7e25) [0x7fcedbe5de25]
  0x7fcedbb8b34d: /lib64/libc.so.6(clone+0x6d) [0x7fcedbb8b34d]
errno = 110 (Connection timed out)
thread = (cache-exp)
thr.req = (nil) {
},
thr.busyobj = (nil) {
},

core dump

(gdb) p *(struct smp_sc *) 0x1cc93d0
$4 = {magic = 2071179018, parent = 0x1cc92f0, bgthread = 139603454985984, flags = 1, stevedore = 0x1cc92f0,
  stats = 0x7ef804006018, fd = 13, filename = 0x1cc8720 "/storage/disk1/varnish_storage_0.bin", mediasize = 16106127360,
  align = 16, granularity = 4096, unique = 263423049, base = 0x7f1268a39000 <**Address 0x7f1268a39000 out of bounds**>,
  ident = 0x7f1268a39020, segments = {vtqh_first = 0x1ce3500, vtqh_last = 0x1ce3518}, cur_seg = 0x1ce3500, next_bot = 4199056,
  next_top = 19938168, free_offset = 19938304, free_pending = 0, thread = 139603454985984, list = {vtqe_next = 0x1cc9a30,
    vtqe_prev = 0x714600 <silos>}, idn = {ss = 0x7f1268a39000, ctx = {state = {3116193388, 529856344, 1257843772, 3710769098,
        2480665922, 431613311, 1358285705, 2595182047}, count = 1088,
      buf = "\000\000\000\300\003", '\000' <repeats 12 times>, "\220\243h\022\177\000\000Varnish Persistent Storage Silo\000xV4\022p\000\000"}, unique = 0, id = 0x4d699a "SILO"}, ban1 = {ctx = {ss = 0x7f1268a3a000, ctx = {state = {3727140139, 2142357566,
          2963079747, 2597783543, 1037774700, 4273242123, 3471749333, 3653854160}, count = 7224080,
        buf = "81c0.jpeg?163630_472262_c976c3be\000\020\000\312\n\000\000\000\032\021"},
      unique = 263423049, id = 0x4d8ca8 "BAN 1"}, start = 0x7f1268a3a020 <**Address 0x7f1268a3a020 out of bounds**>, size = 1048448},
  ban2 = {ctx = {ss = 0x7f1268b3a000, ctx = {state = {3934587700, 407282758, 605264068, 2745377421, 1647408062, 1653083779,
          4021729753, 2451578006}, count = 7224080,
        buf = "81c0.jpeg?163630_472262_c976c3be\000\020\000\312\n\000\000\000\032\021"},
      unique = 263423049, id = 0x4d8cae "BAN 2"}, start = 0x7f1268b3a020 <**Address 0x7f1268b3a020 out of bounds**>, size = 1048448},
  seg1 = {ctx = {ss = 0x7f1268c3a000, ctx = {state = {1779033703, 3144134277, 1013904242, 2773480762, 1359893119, 2600822924,
          528734635, 1541459225}, count = 192,
        buf = "SEG 1\000\000\000I\204\263\017\000\000\000\000\000\240\303h\022\177", '\000' <repeats 41 times>},
      unique = 263423049, id = 0x4d8cb4 "SEG 1"}, start = 0x7f1268c3a020 <**Address 0x7f1268c3a020 out of bounds**>, size = 1048448},
  seg2 = {ctx = {ss = 0x7f1268d3a000, ctx = {state = {1779033703, 3144134277, 1013904242, 2773480762, 1359893119, 2600822924,
          528734635, 1541459225}, count = 192,
        buf = "SEG 2\000\000\000I\204\263\017\000\000\000\000\000\240\323h\022\177", '\000' <repeats 41 times>},
      unique = 263423049, id = 0x4d8cba "SEG 2"}, start = 0x7f1268d3a020 <**Address 0x7f1268d3a020 out of bounds**>, size = 1048448},
  ban1_offset = 0, cond = {__data = {__lock = 0, __futex = 1, __total_seq = 1, __wakeup_seq = 0, __woken_seq = 0,
      __mutex = 0x1ce3408, __nwaiters = 2, __broadcast_seq = 0},
    __size = "\000\000\000\000\001\000\000\000\001", '\000' <repeats 23 times>, "\b4\316\001\000\000\000\000\002\000\000\000\000\000\000", __align = 4294967296}, mtx = {priv = 0x1ce3400}, min_nseg = 10, aim_nseg = 1023, max_nseg = 104851, min_segl = 153569,
  aim_segl = 15739910, max_segl = 1610192889, free_reserve = 314798200}

**Comment by nigoroll** [comment] 2018-09-07 10:28
> Assert error in smp_sml_getobj(), storage/storage_persistent_silo.c line 523:
> Condition((so->ptr) != 0) not true.
this does not match the code as of a068361dff0d25a0d85cf82a6e5fdaf315e06a7d
Please replicate the problem with mainline code

**Comment by nigoroll** [comment] 2018-09-07 10:29
Also a duplicate of #2770 , closing this one

**Closed by nigoroll** 2018-09-07 10:29 UTC
