### ISSUE TITLE
Empty responses with multi-layer setup and grace  (varnish >= 4.1.1)

### ISSUE THREAD

**Issue by ema** [varnishcache/varnish-cache#1956] opened 2016-05-18 12:21 UTC
We have found that varnish occasionally returns empty responses when running in a multi-layer setup (client -> varnish -> varnish -> backend). The issue seems to be grace-related and can only be reproduced on varnish >= 4.1.1.

## Expected Behavior

The response body should be returned to clients.

## Current Behavior

When configured to use another varnish as a backend and with certain grace settings, varnish  occasionally returns responses like:
```
< HTTP/1.1 200 OK
< Server: nginx/1.10.0
< Date: Wed, 18 May 2016 11:30:32 GMT
< Content-Type: text/html
< Last-Modified: Thu, 03 Mar 2016 22:39:39 GMT
< ETag: W/"56d8bd2b-264"
< Vary: Accept-Encoding
< X-Varnish: 94 93
< Age: 4
< Via: 1.1 varnish-v4
< X-Varnish: 65625
< Age: 4
< Via: 1.1 varnish-v4
< Accept-Ranges: bytes
< Content-Length: 612
< Connection: keep-alive
< 
  0   612    0     0    0     0      0      0 --:--:--  0:00:04 --:--:--     0{ [0 bytes data]
* transfer closed with 612 bytes remaining to read
  0   612    0     0    0     0      0      0 --:--:--  0:00:05 --:--:--     0
* Closing connection 0
curl: (18) transfer closed with 612 bytes remaining to read
```

## Possible Solution

We have found that reverting https://github.com/varnishcache/varnish-cache/commit/8b7cb51b76ad616143040ee955f1f6d9306251b9 renders the issue unreproducible.

## Steps to Reproduce (for bugs)

1. Start two varnishds as follows:
    
   ```
   varnishd -a :81 -b localhost:3128 -p default_ttl=4 -p default_grace=1 -F -n frontend
  varnishd -a :3128 -b localhost:80 -p default_ttl=5 -p default_grace=0 -F -n backend
   ```
2. Reproduce the issue with https://phabricator.wikimedia.org/P3122.

A web server listening on localhost:80 and serving some content is needed.

Sample output:
```
61 -> http://localhost:81/
< Age: 0
< Age: 0
SIZE: 612
62 -> http://localhost:81/
< Age: 4
< Age: 4
SIZE: 0
```
Note that the issue disappears when running both varnishes with `default_grace=0`.

The bug does not seem to be reproducable with varnishtest. The following VTC test passes, while I'd expect it to fail. Make sure to pass -b 2048K to varnishtest in order to avoid running out of buffer space.
```
varnishtest "Empty responses with grace"

server s1 {
    loop 120 {
        rxreq
        txresp -body "The quick brown fox jumps over the lazy dog"
    }
} -start

varnish v2 \
    -arg "-p default_ttl=5" \
    -arg "-p default_grace=0" \
    -vcl+backend {} -start

varnish v1 \
    -arg "-p default_ttl=4" \
    -arg "-p default_grace=1" \
    -arg "-b ${v2_addr}:${v2_port}" -start

client c1 {
    loop 120 {
        txreq
        rxresp
        expect resp.status == 200
        expect resp.bodylen == 43
        delay 4
    }
} -run
```

## Context
https://phabricator.wikimedia.org/T134989

## Your Environment

* Version used: 4.1.2
* Operating System and version: Debian Jessie

**Comment by mbgrydeland** [comment] 2016-05-23 14:15
Hi,

Thanks for the detailed bug report. Though I have been unsuccessful trying to reproduce your issue.

I notice that the commit you refer that would "fix" the issue if reverted specifically deals with hit-for-pass objects together with grace. Though it doesn't come clearly through whether the objects in your test are hit-for-pass, regular passes or cache hits. Please clarify.

Also in order to see what is happening when you experience failures it would be very useful if you could get a full varnish log from the two varnish instances during your test run. Please run 'varnishlog -g raw -w frontend.log -n frontend' and a 'varnish -g raw -w backend.log -n backend' while testing and attach them on the ticket.

Regards,
Martin Blix Grydeland

**Comment by ema** [comment] 2016-05-24 10:56
Looks like the request returning an empty response is a miss on the varnishd called "frontend". See Request 32974 and Bereq 32975 in [1956-frontend.log.txt](https://github.com/varnishcache/varnish-cache/files/279246/1956-frontend.log.txt).

[1956-backend.log.txt](https://github.com/varnishcache/varnish-cache/files/279247/1956-backend.log.txt) also included as requested.

**Comment by mbgrydeland** [comment] 2016-05-26 14:03
Thanks for the logs. I believe I understand what's happening now, and this looks very much to me to be a duplicate of #1858. Though #1858 has been fixed and a fix backported to the 4.1 branch which was included in the latest 4.1.2 release. In the ticket description both Varnish 4.1.1 and 4.1.2 is mentioned. Please confirm which Varnish release you are using.

Regards,
Martin Blix Grydeland

**Comment by ema** [comment] 2016-05-26 16:07
I can reproduce the issue with varnish 4.1.2-2~jessie installed from https://repo.varnish-cache.org/debian/

**Closed** 2016-05-30 09:34 UTC

**Comment by hermunn** [comment] 2016-06-09 15:49
Backport review: This needs to be backported, but the progress will be tracked in #1966.

**Comment by hermunn** [comment] 2016-06-16 13:17
Thanks to @mbgrydeland for backporting this the fix to 4.1 in 278b3612be256559330b.

**Comment by lkarsten** [comment] 2016-06-27 13:06
This is in 4.1.3-beta1 and will be applied to 4.1-plus when we get to it.

**Comment by benzvan** [comment] 2020-10-08 20:08
I know this is super old, but I"m seeing similar behavior on varnish 6.4.0-1.el7. I haven't dug into it much, but I'm curious if this bug may have gotten un-fixed at some point.

**Comment by benzvan** [comment] 2020-10-09 15:09
It's 1 out of every 15 million or so responses though, so it's a little tough to really track down.

**Comment by nigoroll** [comment] 2020-10-10 10:26
@benzvan I understand that it is hard to track down, but I am sure you understand that we would need a log showing that is actually is a varnish issue.

**Comment by benzvan** [comment] 2020-10-13 13:58
Yea. I'm trying to figure out how I can get a log from varnishlog for this. What I have right now is log entries from the varnishncsa output.

This is the initial request at the primary varnish node, indicating it was a local miss and that it got its response from varnish6-product-details-6d77f66fb9-ffnqn and it was size: 0.
```
{
  "@timestamp": "2020-10-13T04:23:46+0000",
  "epoch-start-time": "1602563026.294",
  "m": "GET",
  "urlpath": "/product_details/v1/tcin/52483090",
  "q": "",
  "status": 200,
  "handling": "miss",
  "size": 0,
  "storage": "storage.shardlocal",
  "time_us": 1010998,
  "ua": "redsky-adaptive-pdp-api",
  "xrid": "1848033075_151.101.54.180",
  "retries": "0",
  "varnish_redirected": "-",
  "varnish_type": "primary",
  "varnish_request_hop": "2",
  "varnish_shard_cache_info": "primary-miss",
  "varnish_shard_backend": "varnish6-product-details-6d77f66fb9-ffnqn",
  "cache_control": "-",
  "backend_url": "/product_details/v1/tcin/52483090",
  "xkeys": "t52483090",
  "response_reason": "Ok"
}
```

This is the log from varnish6-product-details-6d77f66fb9-ffnqn indicating it was also a miss and it called the real back-end for the response which was size: 2496.
```
{
  "@timestamp": "2020-10-13T04:23:46+0000",
  "epoch-start-time": "1602563026.294",
  "m": "GET",
  "urlpath": "/product_details/v1/tcin/52483090",
  "q": "",
  "status": 200,
  "handling": "miss",
  "size": 2496,
  "storage": "storage.default",
  "time_us": 1010192,
  "ua": "redsky-adaptive-pdp-api",
  "xrid": "1848033075_151.101.54.180",
  "retries": "1",
  "varnish_redirected": "-",
  "varnish_type": "shard",
  "varnish_request_hop": "2",
  "varnish_shard_cache_info": "shard-miss",
  "varnish_shard_backend": "varnish6-product-details-6d77f66fb9-ffnqn",
  "cache_control": "-",
  "backend_url": "/product_details/v1/tcin/52483090",
  "xkeys": "t52483090",
  "response_reason": "Ok"
}
```

Note this is different from the original issue in that neither node indicates a `grace` status in the `varnish_shard_cache_info` field.
