### ISSUE TITLE
varnish does not play well with jemalloc-5.0

### ISSUE THREAD

**Issue by ingvarha** [varnishcache/varnish-cache#2521] opened 2017-12-14 13:50 UTC
This was tested by building both varnish-5.2.1 and the varnish git master branch against jemalloc-5.0.1, on x86_64. varnish builds fine, but the test suite fails badly.

jemalloc-5.0 will be included in the next Fedora release, ie. f28 and onwards.

I have added the log only for the git master branch build.

Testsuite summary for Varnish trunk

 TOTAL: 648
 PASS:  238
 SKIP:  5
 XFAIL: 0
 FAIL:  405
 XPASS: 0
 ERROR: 0

See bin/varnishtest/test-suite.log
Please report to varnish-dev@varnish-cache.org

**Comment by ingvarha** [comment] 2017-12-14 13:51
[test-suite.log](https://github.com/varnishcache/varnish-cache/files/1559412/test-suite.log)

**Comment by ingvarha** [comment] 2017-12-21 15:44
Interesting details (thanks, @slimhazard): This is quite arch specific.

- i686, ppc64, ppc64le, and s390x all works fine.
- Building varnish with --disable-pcre-jit hides the bug on x86_64

So clearly, this is a pcre-jit specific problem on x86_64

**Comment by fgsch** [comment] 2018-01-01 14:16
What is the pcre version this was compiled against?

**Comment by fgsch** [comment] 2018-01-02 09:44
Nevermind. I can reproduce this.

Looks like this started with https://github.com/jemalloc/jemalloc/commit/36bd90b96212772f1adbd421a6b091b542278995.

Still investigating.

**Comment by uhliarik** [comment] 2018-01-24 17:46
@fgsch Hi Federico, any news?

**Comment by bsdphk** [comment] 2018-02-07 10:10
As is, I don't see any indication that this is our problem.

I have added a TODO item for the release in #2438 to document this issue in release notes.

**Comment by fgsch** [comment] 2018-02-19 12:50
Reopening for now. I will take another look before 6.0.

**Comment by ingvarha** [comment] 2018-03-06 21:14
Looks like this pcre/jemalloc problem was fixed in jemalloc by letting it support different pagesizes: https://github.com/jemalloc/jemalloc/pull/769

I will test new varnish builds as soon as I have gotten an updated jemalloc into fedora rawhide.

**Comment by fgsch** [comment] 2018-04-14 23:44
@ingvarha did you manage to try this?

**Comment by fgsch** [comment] 2018-05-03 04:39
ping @ingvarha

**Comment by ingvarha** [comment] 2018-05-04 13:52
I have incorperated the fix for jit/pcre in jemalloc into fedora. varnish-6.0.0 runs the test suite without problems on that jemalloc.

@Dridi Can you verify that this fixes your problem as well? Fix should be in fedora's jemalloc-5.0.1-5.

**Comment by Dridi** [comment] 2018-05-04 14:01
I had the problem with that version: https://github.com/varnishcache/varnish-cache/issues/2667#issuecomment-386203027

**Comment by bsdphk** [comment] 2018-06-13 07:48
Timing this out, consider moving to the packaging repo if still relevant.

**Closed by bsdphk** 2018-06-13 07:48 UTC
Labels: r=6.0
