### ISSUE TITLE
Health probes fail when HTTP response does not contain reason phrase

### ISSUE THREAD

**Issue by philipseidel** [varnishcache/varnish-cache#2069] opened 2016-09-01 20:58 UTC
## Expected Behavior
When an HTTP server responds with a valid HTTP status code and no reason phrase a Varnish health probe should consider it valid.

## Current Behavior
Some application servers are starting to drop support for the reason phrase in an HTTP response.  The spring-boot project is one example: https://github.com/spring-projects/spring-boot/issues/6548.  These updates are resulting in failed health probes since the response message does not contain a reason phrase `HTTP/1.1 200` vs. `HTTP/1.1 200 OK`.

## Possible Solution
Accept HTTP responses that don't contain a reason phrase as valid as RFC-2616 states that `The client is not required to examine or display the Reason- Phrase.`  I am not sure I agree with this but that is how some projects are interpreting the spec.

## Steps to Reproduce (for bugs)
* Create a text file with the following markup.
```
HTTP/1.1 200

Hello World!
```
* Run simple netcat server `while true ; do nc -l 80  < test.html ; done`
* Create simple VCL
```
backend default {
  .host = "127.0.0.1";
  .port = "http";
  .probe = {
    .url = "/";
    .window = 8;
    .threshold = 3;
    .initial = 3;
  }
}
```
* Reload/Start varnish
* Watch backend health statistics `watch 'varnishadm debug.health'` and notice the *Happy* row will have the backend as `-` rather than `H`.
* Update the text file to include a reason phrase.
```
HTTP/1.1 200 WOOT

Hello World!
```
* Backend statistics should now be reporting `H`.

## Context
It would seem that some are interpreting the spec as though the reason phrase is not required since the client shouldn't be required to examine it.  If things continue to go this direction it will be hard to upgrade components that run behind Varnish and follow this pattern.

## Your Environment
* Version used: 3.0.7
* Operating System and version: Red Hat Enterprise Linux Server release 6.7 (Santiago)

**Comment by Dridi** [comment] 2016-09-01 23:08
Varnish 3.0 is EOL, and so will 4.0 in two weeks. You should upgrade to 4.1 as this won't be fixed.

**Closed by Dridi** 2016-09-01 23:08 UTC

**Comment by philipseidel** [comment] 2016-09-01 23:23
Is it an issue in 4.1?

**Comment by Dridi** [comment] 2016-09-01 23:57
It seems to work fine with 4.1.3, this test case passes:

```perl
varnishtest "Test for #2069"

server s1 -repeat 20 {
	rxreq
	send "HTTP/1.1 200\r\n\r\nHello World!"
	accept
} -start

varnish v1 -vcl {
	backend s1 {
		.host = "${s1_addr}";
		.port = "${s1_port}";
		.probe = {
			.interval = 50ms;
			.initial = 0;
		}
	}
} -start

delay 2

varnish v1 -expect VBE.vcl1.s1.happy > 0
```

**Comment by behinam** [comment] 2017-05-07 08:19
I have a varnish server with 3 backends. all backends are apache. everything is ok and the varnish server caches everything I need, and the connections are OK. I wnat to monitor the health of web servers. and in case of a failure, varnish does not send reuests to the failed web server. The problem is that when I enable the probe for all backedns I get the 503 error! If i enablle it on one or two backends, everything is OK, but when I enable it for 3 backends I get the 503 error.
here's varnish configuration for backends and health checking:

vcl 4.0;

import directors;

probe backend_healthcheck {
   .url = "/";
   .timeout = 34 ms;
   .window = 5;
   .threshold = 3;
   .interval = 1s;

}

backend web1 {
    .host = "192.168.1.16";
    .port = "8080";
    .probe = backend_healthcheck;
}

backend web2 {
    .host = "192.168.1.18";
    .port = "8080";
    .probe = backend_healthcheck;
}

backend web3 {
    .host = "192.168.1.20";
    .port = "8080";
    .probe = backend_healthcheck;
}
 
 sub vcl_init {
    new apache = directors.round_robin();
    apache.add_backend(web1);
    apache.add_backend(web2);
    apache.add_backend(web3);
}

**Comment by hermunn** [comment] 2017-05-21 15:06
Backport review: The commit 6768c37 was backported as 9367a6329e67.
