### ISSUE TITLE
h2-support + range-handling 

### ISSUE THREAD

**Issue by sheesupport** [varnishcache/varnish-cache#2473] opened 2017-10-27 00:22 UTC
range handling with +http2 feature as decribed here:

https://varnish-cache.org/lists/pipermail/varnish-misc/2017-September/026136.html

seems to have a bug as partially confirmed here:

https://varnish-cache.org/lists/pipermail/varnish-misc/2017-September/026158.html

Branch: varnish-5.1.2; Config: mostly default

**Comment by daghf** [comment] 2017-10-27 12:14
Could you tell us a bit more or give an example of what the problem is?

I tried a simple test case w/ h2 & ranges, and it seems to work as expected.

```
varnishtest "#2473: h/2 range"

server s1 {
	rxreq
	txresp -body "foobar"
} -start


varnish v1 -vcl+backend {} -start
varnish v1 -cliok "param.set feature +http2"

client c1 {
	stream 1 {
		txreq -hdr "range" "bytes=0-1"
		rxresp
		expect resp.status == 206
		expect resp.http.content-length == 2
		expect resp.body == "fo"
	} -run

	stream 3 {
		txreq -hdr "range" "bytes=2-"
		rxresp
		expect resp.status == 206
		expect resp.http.content-length == 4
		expect resp.body == "obar"
	} -run
} -run
```

**Comment by sheesupport** [comment] 2017-10-27 14:22
This post describes it more closely: 
https://varnish-cache.org/lists/pipermail/varnish-misc/2017-September/026132.html

Its specific to iOS/OSX/Safari clients (compared to Firefox they use range requests).
Mentioned clients do not have problems when using http/1.1 connections. 
It's not clear who of both parties are not compliant.

**Comment by daghf** [comment] 2017-10-30 15:23
I have a hunch that this is related to the fact that the 5.2.0 release does not respect client flow control window limits. This is known to cause problems when transferring larger objects in that the clients hang up when they notice Varnish is sending too fast.

This has since been implemented (0d3044d4f3c18935049ad0e954edbacafa055557), and it would be interesting to see if that solves your problem.

We're in the process of rolling out weekly master package builds. In the meantime could I convince you to give current master a try?

**Comment by sheesupport** [comment] 2017-10-30 16:37
Could you provide the corresponding patch (diff) against the 5.2.0-branch? 
That helps me to incorporate it into our packaging build process ... thanks.

**Comment by daghf** [comment] 2017-10-31 10:01
@sheesupport 

You need commits 58b40c4f0c9d38951ec37ef713798fee33f427d2, 3a86dd8a7b9c0d3fb8b2794d9cc3eec99f24b2df and 0d3044d4f3c18935049ad0e954edbacafa055557. They apply cleanly against the 5.2 branch.

For convenience I've squashed the three commits into a single patch available here, https://filebin.varnish-software.com/qy3i987ccfr917rb/0001-Make-senders-wait-in-H2_Send-when-out-of-window-cred.patch

**Comment by klenan** [comment] 2017-11-03 13:36
I've encountered this issue as well using Varnish 5.2.0-1.el7 on CentOS 7.4 with HTTP/2 clients requesting larger (>50M) videos where HTTP/1.1 worked fine. Traffic analysis showed clients sending lots of TCP zero windows indicating full receive buffers and Varnish would eventually `RST` the client connection, further tests confirmed streaming over HTTP/2 to be broken for all clients. Hitch 1.4.6 as client in this case logged the aforementioned reset as well:

    Oct 27 17:09:26 hostname hitch[7848]: 20171027T170926.949851 [ 7857] {backend} Socket error: Connection reset by peer

@daghf 7180e00 (parent of your patches) fixes this.

**Comment by sheesupport** [comment] 2017-11-04 23:17
Thank you for providing the patch file. 

Comparing the behaviour with and without this patch (5.2 release) and switching back and forth, I can conclude; that the clients do not have any issues so far (qualitatively), that are served by a 
varnish instance that have the mentioned patch applied. With h2 or http/1.1 they behave the same way.

Switching back to a varnish instance without the patch and taking a look at the hitch node, I see also the mentioned "{backend} Socket error: Connection reset by peer" appearing while requesting mp4 files (they do not appear with a patched varnish).

So the patch addresses this issue. Thats great, thank you.

**Comment by daghf** [comment] 2017-11-06 10:02
@sheesupport @klenan, thanks a lot for confirming.

I'll close this issue now.

**Closed by daghf** 2017-11-06 10:02 UTC
