### ISSUE TITLE
Varnish does not read file storage on restart (resets collected cache)

### ISSUE THREAD

**Issue by aiboost** [varnishcache/varnish-cache#4147] opened 2024-08-01 09:34 UTC
### Expected Behavior

When I restart Varnish it must re-read my file with previously collected cache (I specified the file `/var/lib/varnish/myservice.bin`). 

Are my expectations even correct?

### Current Behavior

When I call `/etc/init.d/varnish restart`, it ignores storage file and starts collecting cache from the scratch updating this file.

### Steps to Reproduce (for bugs)

1. Start the backend and Varnish
2. Call some cachable URL
3. Stop the backend <-- Varnish still returns this cached URL, it's correct
4. Restart Varnish <-- Varnish returns "Error 503 Backend fetch failed" 

### Context

I wish to archive both speed and fail-safe working of my service.
When service is down, Varnish is the only thing that can let working to all my clients. I'm in doubt why the file storage's initial content is ignored on the start of Varnish.

Now I'm configuring only Varnish with `-s file,/var/lib/varnish/myservice.bin,10G` option, but later I plan to use a combination of: `backend` <-- `Varnish (file)` (saving a state) <-- `Varnish (malloc)` (boosting the speed) or like that.

### Varnish Cache version

varnishd (varnish-6.2.1 revision 9f8588e4ab785244e06c3446fe09bf9db5dd8753)

### Operating system

Ubuntu20.04

**Comment by walid-git** [comment] 2024-08-01 09:58
> Are my expectations even correct?

They are not : https://github.com/varnishcache/varnish-cache/blob/master/doc/sphinx/reference/varnishd.rst?plain=1#L395

> -s <file,path[,size[,granularity[,advice]]]>
>
> The file backend stores data in a file on disk. The file will be
> accessed using mmap. **_Note that this storage provide no cache persistence_**.

**Comment by nigoroll** [comment] 2024-08-01 10:22
[SLASH/fellow](https://gitlab.com/uplex/varnish/slash) might be what you want.

Closing this ticket because, as walid already explained, you reported the file storage as working as designed.

**Closed by nigoroll** 2024-08-01 10:22 UTC

**Comment by aiboost** [comment] 2024-08-09 14:15
> [SLASH/fellow](https://gitlab.com/uplex/varnish/slash) might be what you want.
> 
> Closing this ticket because, as walid already explained, you reported the file storage as working as designed.

I just wish to confirm that "fellow" storage type worked like a charm for me, thanks for the advice!

P. S.: It would be nice if Slash module had a precompiled version shipped with Varnish itself (or in a separate DEB/RPM package) located in official Varnish repo or even in popular distros (e.g. Ubuntu) repos (at least after their new version is released).
But anyway I appreciate all efforts you guys make developing Varnish.
