### ISSUE TITLE
Bug - when Varnish  fill its memory, server crashes

### ISSUE THREAD

**Issue by kaaaq** [varnishcache/varnish-cache#3139] opened 2019-11-19 10:14 UTC
Hi
On Varnish i use ram as backend for storage Caching,when Reqests comes to it, after a while the amount of server's ram begans to full little by little and after it completely fills, the server crashes and again it starts caching in the ram.

I assign following variables in systemd service file for varnish.service but still it does its Previous behavior and it crashs again:

LimitMEMLOCK=14336
MemoryLimit=13G
MemoryHigh=13G
MemoryMax=13G

How can i limit and specify the special amonut of memory that it cant exceed from that?

****This is important for me that when the amount of ram get fill, varnish start removing the old object from the end of ram and insert new object to ram and server doesn't crash.****
Thanks for your help

#Version used:
Varnishv4.1
#Operating System and version:
Ubuntu16.04
#Source of binary packages used (if any)
Installed from official ubuntu packages

**Comment by Dridi** [comment] 2019-11-19 10:24
This is a duplicate of #3138 and stating bug in the subject doesn't make it more relevant.

I'll let someone else decide whether to close or not, I still insist that this is a discussion for the varnish-misc mailing list. Reminder, Varnish 4.1 is no longer supported.

**Comment by nigoroll** [comment] 2019-11-19 10:27
I agree that this is not a bug report. The basic information requested in the bug template is missing.

**Closed by nigoroll** 2019-11-19 10:27 UTC
