### ISSUE TITLE
varnishstat cannot access attributes of type MAIN anymore through field inclusion

### ISSUE THREAD

**Issue by zstyblik** [varnishcache/varnish-cache#2182] opened 2017-01-12 07:41 UTC
Hello,

it seems that varnishstat cannot access type MAIN anymore via field inclusion, resp. `-f MAIN.<attribute>`.

## Expected Behavior

The following works with varnish 4.x:

```
/usr/bin/varnishstat -j -f 'MAIN.cache_hit' -f 'MAIN.cache_hitpass' -f 'MAIN.cache_miss'
{
        "timestamp": "2017-01-12T07:37:22",
        "MAIN.cache_hit": {"type": "MAIN", "value": 60281094, "flag": "a", "description": "Cache hits"},
        "MAIN.cache_hitpass": {"type": "MAIN", "value": 410258, "flag": "a", "description": "Cache hits for pass"},
        "MAIN.cache_miss": {"type": "MAIN", "value": 24050702, "flag": "a", "description": "Cache misses"}
}
```
## Current Behavior

However, the same does not with varnish 5.0:

```
/usr/bin/varnishstat -j -f 'MAIN.cache_hit' -f 'MAIN.cache_hitpass' -f 'MAIN.cache_miss'
{
  "timestamp": "2017-01-12T07:38:16",

}
```

Funny enough, the following works:

```
/usr/bin/varnishstat -j -f '*.cache_hit' -f '*.cache_hitpass' -f '*.cache_miss'
{
  "timestamp": "2017-01-12T07:38:47",
  "MAIN.cache_hit": {
    "description": "Cache hits",
    "type": "MAIN", "flag": "c", "format": "i",
    "value": 16035291
  },
  "MAIN.cache_hitpass": {
    "description": "Cache hits for pass",
    "type": "MAIN", "flag": "c", "format": "i",
    "value": 139319
  },
  "MAIN.cache_miss": {
    "description": "Cache misses",
    "type": "MAIN", "flag": "c", "format": "i",
    "value": 6824973
  }
}
```

## Context

Scraping metrics in not exactly the best way. :)

## Your Environment

```
varnishd -V
varnishd (varnish-5.0.0 revision 99d036f)
Copyright (c) 2006 Verdens Gang AS
Copyright (c) 2006-2015 Varnish Software AS

varnishstat (varnish-5.0.0 revision 99d036f)
Copyright (c) 2006 Verdens Gang AS
Copyright (c) 2006-2015 Varnish Software AS
```

at Debian 8 Jessie.

**Comment by gquintard** [comment] 2017-01-12 08:57
duplicate of #2118

**Closed by gquintard** 2017-01-12 08:57 UTC

**Comment by zstyblik** [comment] 2017-01-12 10:16
Sorry about duplicate on closed task. Only if github search didn't suck so hard. I'm glad to see it's fixed! Thanks @gquintard.

**Comment by gquintard** [comment] 2017-01-12 10:28
No problem, that happens. I just knew about it because I saw it before.

**Comment by hermunn** [comment] 2017-01-24 10:48
Backport review: Nothing commited, nothing to backport / duplicate of #2118.
