### ISSUE TITLE
Average Hitrate Reported by Varnishstat Inaccurate

### ISSUE THREAD

**Issue by bsdphk** [varnishcache/varnish-cache#1859] opened 2016-03-04 13:32 UTC
Old ticket imported from Trac
See archived copy here: https://varnish-cache.org/trac/ticket/1859

**Comment by aondio** [comment] 2016-07-06 12:46
@lkarsten do you know if the original report is present on github?

Looking at the details in the ticket, It seems he/she compares an absolute hit-rate with one evaluated on a delta time. To me it makes completely sense that an averaged hit-rate can report a value very different from the averaged one.

I've also reviewed all the changes between VC4.0.3 and VC4.1.1 and the hit-rate calculation or anything strictly related to how we calculate those numbers have been changed.

I can quite easily reproduce what the reporter is experiencing:
* start varnish
* siege it
* stop siege
* let varnish run for a while
in less than 5 minutes uptime we can get a quite high absolute hit-rate, but very depressing values when it comes to the 10/100/1000 updates averages.

**Comment by batliner** [comment] 2016-07-08 17:02
Hi @aondio,

At the time of testing I had three different versions of varnish running behind a load balancer using a least connection algorithm.  Two were running 3.0.3 and the other 4.1.1.  They were restarted at similar times and I was looking at the varnishstat hit-rate metrics on each.

This is in the original report, but adding it here as well so that it is easier to see:

**The average hit rate according to varnish 4.1.1 is**: 0.2465 0.3085 0.3127
**The average hit rate according to varnish 3.0.3 is**: 0.6592 0.6402 0.6182

**Here is a varnishstat -1 dump from each server**
varnishstat -1 4.1.1:  http://pastebin.com/tP5AE995 
varnishstat -1 3.0.3:  http://pastebin.com/cg51CuUS

After this, I upgraded one of the two 3.0.3 servers to 4.0.3 for testing.  I had 3.0.3, 4.0.3 and 4.1.1 all running in the load balancer.  The 4.0.3 server was reporting a similar hit-rate in varnishstat as the 3.0.3 server.  It was only the server running 4.1.1 that was different (significantly lower).  Below is the varnishtat averages for the 4.0.3 and 4.1.1 servers after they had been running for 5 minutes.  They were restarted at the same time.

**Hit-rate for 4.0.3 according to varnishstat**
Hitrate n:       10          100	 299
avg(n):           0.6947   0.6813   0.6921

**Hit-rate for 4.1.1 according to varnishstat**
Hitrate n:       10          100	 305
avg(n):           0.1956   0.1585   0.1578

At first, I thought I had messed something up with the 4.x upgrade and was caching at a much lower hit-rate.  That would be bad!  In the original report I was looking at the absolute hit-rate to ensure that I was in fact caching at a similar hit-rate as the previous versions.  It also allowed me to get a gauge of which delta time hit-rate seemed accurate.  The absolute hit-rate calculations from 3.0.3 and 4.0.3 seemed to line up with what varnishstat was reporting.  That was not the case with the asbolute hit-rate calculation from 4.1.1 when comparing it to what varnishstat was reporting.  Since all servers were running side by side in the load balancer and 4.1.1 showed a different varnishstat value than the others, it seems that there is something different with the reporting of the hit-rate in 4.1.1.

Hope this helps and please let me know if you need more information!

**Comment by aondio** [comment] 2016-07-11 07:17
Hi @batliner, that's an excellent report.
I'll try to reproduce what you describe and check if I spot where the problem lies.

Thanks.

**Comment by aondio** [comment] 2016-07-28 14:45
Hi @batliner, I took a second look at the code.
There obviously major differences between 3.x and 4.0, but almost no differences between 4.0 and 4.1 and, that's where I've focused my attention(based on the explanation in your report).

No changes on the way the hit-rate is calculated happened between 4.0 and 4.1 and this makes more  difficult to spot a potential bug.
I've labeled this issue with the "help wanted" tag in the hope that someone else will have the chance to have a look at the source code, new eyes bring new perspectives.

**Comment by pdufour** [comment] 2016-08-09 16:47
Seeing this same issue. Running a `varnishlog` which shows hit / miss status of urls and comparing to varnishstat Hitrate avg and they are wildly different.

**Comment by aondio** [comment] 2016-10-17 14:02
Removing myself from as assignee.
I've reviewed the code once more and found nothing wrong that could explain what the reporters are experiencing.

Input and help is very appreciated.

**Comment by nigoroll** [comment] 2017-11-10 19:25
I have not traced this issue over time, but I am very sure that it does does not exist in master any more. For production systems under my control, the hitrate reported in varnishstat (curses mode) very precisely matches the hitrate calculated externally (in grafana based on varnishstat) as cache_hit / (cache_hit + cache_miss).
I will thus close this ticket. If you believe this is in error, please drop comment and/or re-open.

**Closed by nigoroll** 2017-11-10 19:25 UTC
Labels: a=help wanted

**Comment by nigoroll** [comment] 2017-11-10 19:26
please note that in 5.2 #2430 prevents accurate hitrate calculation
