### ISSUE TITLE
Varnish crashed with "Assert error in ban_lurker_test_ban()"

### ISSUE THREAD

**Issue by vmasutin** [varnishcache/varnish-cache#1949] opened 2016-05-12 12:45 UTC
## Your Environment

* Version used: 4.1.2 (4.1.2-2~jessie)
* Operating System and version:
debian 8.4 amd64
varnish installed from repo.varnish-cache.org

Occasionally I can see varnish crashing with "Assert error in ban_lurker_test_ban()"
Let me know if you need additional info to narrow down this problem.
Please find backtrace from logs below.

May 12 07:20:18 web-cache varnishd[30207]: Child (30208) died signal=6
May 12 07:20:18 web-cache varnishd[30207]: Child (30208) Last panic at: Thu, 12 May 2016 07:20:18 GMT
#012"Assert error in ban_lurker_test_ban(), cache/cache_ban_lurker.c line 149:
#012  Condition((((obans)->vtqh_first == ((void *)0))) == 0) not true.
#012thread = (ban-lurker)
#012version = varnish-4.1.2 revision 0d7404e
#012ident = Linux,3.16.0-4-amd64,x86_64,-junix,-sfile,-smalloc,-hcritbit,epoll
#012Backtrace:
#012  0x433db5: varnishd() [0x433db5]
#012  0x419c54: varnishd(ban_lurker+0x944) [0x419c54]
#012  0x449792: varnishd() [0x449792]
#012  0x7f26935110a4: libpthread.so.0(+0x80a4) [0x7f26935110a4]
#012  0x7f269324687d: libc.so.6(clone+0x6d) [0x7f269324687d]#012#012"

**Comment by Dridi** [comment] 2016-05-12 12:58
Duplicate of #1919, closing.

**Comment by Dridi** [comment] 2016-05-12 12:59
It doesn't crash on the same line, summoning @nigoroll.

**Comment by nigoroll** [comment] 2016-05-13 10:47
It is exactly the same line as in #1919 , except that I opened that ticket for a master version with additional changes merged

**Closed by nigoroll** 2016-05-13 10:47 UTC

**Comment by hermunn** [comment] 2016-06-07 12:34
Trusting @nigoroll, I will remove the backport-review tags since this is the same as #1919.
