### ISSUE TITLE
Missing command entries in varnishadm help menu, on Varnish 6.0

### ISSUE THREAD

**Issue by cyberaa** [varnishcache/varnish-cache#2682] opened 2018-05-17 17:59 UTC
## Current Behavior

With Varnish 6.0, while using **varnishadm help** it appears some command entries are missing.

This can be misleading leading to believe something has changed on new versions.

i.e.

- param.show
- param.set
- panic.show
- panic.clear [-z]
- banner
- storage.list
...

```
varnish-6.0.0 revision a068361dff0d25a0d85cf82a6e5fdaf315e06a7d
 
Type 'help' for command list.
Type 'quit' to close CLI session.
 
varnish> help
200        
auth <response>
backend.list [-p] [<backend_pattern>]
backend.set_health <backend_pattern> [auto|healthy|sick]
ban <field> <operator> <arg> [&& <field> <oper> <arg> ...]
ban.list
help [<command>]
ping [<timestamp>]
quit
start
vcl.discard <configname|label>
vcl.label <label> <configname>
vcl.list
vcl.load <configname> <filename> [auto|cold|warm]
vcl.show [-v] <configname>
vcl.state <configname> [auto|cold|warm]
vcl.use <configname|label>
```

## Expected Behavior

Like previous versions, the menu should look like this:

```
Type 'help' for command list.
Type 'quit' to close CLI session.
 
varnish> help
200        
help [<command>]
ping [<timestamp>]
auth <response>
quit
banner
status
start
stop
vcl.load <configname> <filename> [auto|cold|warm]
vcl.inline <configname> <quoted_VCLstring> [auto|cold|warm]
vcl.use <configname>
vcl.state <configname> [auto|cold|warm]
vcl.discard <configname>
vcl.list
param.show [-l] [<param>]
param.set <param> <value>
panic.show
panic.clear [-z]
storage.list
vcl.show [-v] <configname>
backend.list [-p] [<backend_expression>]
backend.set_health <backend_expression> <state>
ban <field> <operator> <arg> [&& <field> <oper> <arg> ...]
ban.list
```

## Steps to Reproduce (for bugs)

1. Run varnishadm help

## Your Environment

* Version used: Varnish 6.0.0
* Operating System and version: Ubuntu 16.04.3 LTS (Xenial)

**Comment by fgsch** [comment] 2018-05-17 18:05
I can reproduce it locally.
These fields are hidden when we start the child.

**Comment by fgsch** [comment] 2018-05-17 18:10
Test:
```
varnishtest ""

server s1 {

} -start

varnish v1 -vcl+backend {

} -start

shell -match "param.set" {
        varnishadm -n ${tmpdir}/v1 help
} -start

varnish v1 -stop

shell -match "param.set" {
        varnishadm -n ${tmpdir}/v1 help
} -start
```

**Comment by Dridi** [comment] 2018-05-18 06:25
That's always been the expected behavior to me, we only get the full set of commands when the child is started. I think we should close this with a docfix in the `help` command's description.

**Comment by Dridi** [comment] 2018-05-18 06:28
OK, I see now that some of the missing commands should be available when the child is not running.

**Comment by fgsch** [comment] 2018-05-18 07:14
The problem is that are not visible when the child is running (not the opposite).
Please see the test.

**Comment by bsdphk** [comment] 2018-05-18 08:16
This is actually a result of how the CLI engine works.

The mgt has a list of commands, and if it doesn't match the input, it is sent to the worker.

In order to show the possible commands, mgt will have to merge its own list with a (json?) response from the worker.

**Comment by fgsch** [comment] 2018-05-18 11:08
`varnishadm help` output before and after the child is running:
```
 auth <response>
-banner
+backend.list [-p] [<backend_pattern>]
+backend.set_health <backend_pattern> [auto|healthy|sick]
+ban <field> <operator> <arg> [&& <field> <oper> <arg> ...]
+ban.list
 help [<command>]
-panic.clear [-z]
-panic.show
-param.set <param> <value>
-param.show [-l] [<param>]
 ping [<timestamp>]
 quit
 start
-status
-stop
-storage.list
 vcl.discard <configname|label>
-vcl.inline <configname> <quoted_VCLstring> [auto|cold|warm]
 vcl.label <label> <configname>
 vcl.list
 vcl.load <configname> <filename> [auto|cold|warm]
+vcl.show [-v] <configname>
 vcl.state <configname> [auto|cold|warm]
 vcl.use <configname|label>
```

**Comment by nigoroll** [comment] 2018-05-22 11:19
bugwash:
* implement help -j in child
* in master, parse and format

**Closed** 2018-08-13 08:52 UTC
