### ISSUE TITLE
SPARC Solaris 11.3/Solaris Studio 12.4, 9 of 513 tests failed when compiled with -m64

### ISSUE THREAD

**Issue by skrueger8** [varnishcache/varnish-cache#2050] opened 2016-08-23 13:44 UTC
## Expected Behavior
All tests pass

## Current Behavior
9 of 513 tests failed

```
FAIL: tests/b00033.vtc (exit: 2)
FAIL: tests/c00006.vtc (exit: 2)
FAIL: tests/c00019.vtc (exit: 2)
FAIL: tests/c00021.vtc (exit: 2)
FAIL: tests/r00502.vtc (exit: 2)
FAIL: tests/r00984.vtc (exit: 2)
FAIL: tests/r01030.vtc (exit: 2)
FAIL: tests/v00011.vtc (exit: 2)
FAIL: tests/v00039.vtc (exit: 2)


```

## Possible Solution
Compiling without `-m64` makes no test fail

## Steps to Reproduce (for bugs)
1. grab the latest master
2. MAKE=gmake CFLAGS='-m64' LDFLAGS='-m64' ./configure
3. gmake
4. gmake check

## Your Environment
* Version used: master (2016-08-23)
* Operating System and version: Solaris 11.3 SRU 10.5

**Comment by skrueger8** [comment] 2016-08-23 13:45
[test-suite.log.txt](https://github.com/varnishcache/varnish-cache/files/432535/test-suite.log.txt)

**Comment by nigoroll** [comment] 2016-08-23 13:51
@skrueger8 this is on SPARC, right? If so, this may be a helpful hint to alignment issues we still have due to the strict alignment rules on SPARC

**Comment by skrueger8** [comment] 2016-08-23 13:54
Yes this is on SPARC hardware

**Comment by nigoroll** [comment] 2016-08-23 13:56
The common stack trace element is `ban_evaluate`->`pcre_exec` so I'll check if we have an alignment issue there. Otherwise this could also be an issue in libpcre. can you please call `mdb <varnishd-binary> <core>` and send me the output of:
* `::regs`
* `libpcre.so.0.0.0'pcre_exec::dis`

**Comment by skrueger8** [comment] 2016-08-23 14:15
[varnishd_cores.txt](https://github.com/varnishcache/varnish-cache/files/432616/varnishd_cores.txt)

**Comment by nigoroll** [comment] 2016-08-23 14:17
This should be fixed in master, can you please re-check?
I'd only need the mdb output I asked for before if the issue is still present. Thx.

**Comment by nigoroll** [comment] 2016-08-23 14:30
thanks for the core diagnostics, but the process ids of the cores seem not to match the test suite log. In case this is still present, would you please send matching info? Thanks, Nils

**Comment by skrueger8** [comment] 2016-08-23 14:43
> thanks for the core diagnostics, but the process ids of the cores seem not to match the test suite log. In case this is still present, would you please send matching info? Thanks, Nils

Sorry, I had to rebuild with `CFLAGS='-m64 -g'` to actually get any core files...

Anyway, 984f145 looks good

```
All 513 tests passed
```

Thanks!

**Comment by Dridi** [comment] 2016-08-23 21:11
c19 consistently fails on my system with 984f145:

```
**   top   1.1 === varnish v1 -expect bans_added == 6
**   v1    1.1 as expected: bans_added (6) == 6
**   top   1.1 === varnish v1 -expect bans_dups == 3
---- v1    2.1 Not true: bans_dups (2) == 3 (3)
```

**Comment by skrueger8** [comment] 2016-08-24 06:44
Now that you mention it, I have *some* failed tests on amd64 Solaris 11.3/Studio 12.5 (compiled with -m64) as well:

```
FAIL: tests/b00001.vtc
FAIL: tests/b00002.vtc
FAIL: tests/b00017.vtc
FAIL: tests/b00018.vtc
FAIL: tests/b00019.vtc
FAIL: tests/b00030.vtc
FAIL: tests/b00038.vtc
FAIL: tests/b00048.vtc
FAIL: tests/c00010.vtc
FAIL: tests/c00012.vtc
FAIL: tests/c00015.vtc
FAIL: tests/c00028.vtc
FAIL: tests/c00036.vtc
FAIL: tests/c00048.vtc
FAIL: tests/c00055.vtc
FAIL: tests/c00056.vtc
FAIL: tests/c00061.vtc
FAIL: tests/c00063.vtc
FAIL: tests/c00064.vtc
FAIL: tests/c00068.vtc
FAIL: tests/c00077.vtc
FAIL: tests/d00001.vtc
FAIL: tests/d00002.vtc
FAIL: tests/d00003.vtc
FAIL: tests/d00005.vtc
FAIL: tests/d00010.vtc
FAIL: tests/e00018.vtc
FAIL: tests/l00004.vtc
FAIL: tests/m00023.vtc
FAIL: tests/r00495.vtc
FAIL: tests/r00558.vtc
FAIL: tests/r00561.vtc
FAIL: tests/r00590.vtc
FAIL: tests/r00612.vtc
FAIL: tests/r00769.vtc
FAIL: tests/r00789.vtc
FAIL: tests/r00801.vtc
FAIL: tests/r00803.vtc
FAIL: tests/r00806.vtc
FAIL: tests/r00915.vtc
FAIL: tests/r00961.vtc
FAIL: tests/r01030.vtc
FAIL: tests/r01157.vtc
FAIL: tests/r01206.vtc
FAIL: tests/r01287.vtc
FAIL: tests/r01296.vtc
FAIL: tests/r01349.vtc
FAIL: tests/r01350.vtc
FAIL: tests/r01367.vtc
FAIL: tests/r01417.vtc
FAIL: tests/r01478.vtc
FAIL: tests/r01493.vtc
FAIL: tests/r01512.vtc
FAIL: tests/r01562.vtc
FAIL: tests/r01612.vtc
FAIL: tests/r01638.vtc
FAIL: tests/r01641.vtc
FAIL: tests/r01660.vtc
FAIL: tests/r01684.vtc
FAIL: tests/r01730.vtc
FAIL: tests/r01806.vtc
FAIL: tests/r01878.vtc
FAIL: tests/r01881.vtc
FAIL: tests/r01890.vtc
FAIL: tests/r01927.vtc
FAIL: tests/r01956.vtc
FAIL: tests/v00012.vtc
FAIL: tests/v00014.vtc
FAIL: tests/v00016.vtc
FAIL: tests/v00018.vtc
FAIL: tests/v00040.vtc
FAIL: tests/v00048.vtc

72 of 513 tests failed
[test-suite.log.txt](https://github.com/varnishcache/varnish-cache/files/434151/test-suite.log.txt)
```

c19 is fine though:

```
PASS: tests/c00019.vtc
```

**Comment by nigoroll** [comment] 2016-08-24 07:57
will check asap

**Comment by nigoroll** [comment] 2016-08-24 09:09
@Dridi c19 should be ok again now.
@skrueger8 looking at amd64 + suncc now

**Comment by nigoroll** [comment] 2016-08-24 09:13
@skrueger8 from your log:
`**** v1    0.2 CLI RX| "vgc.c", line 1390: statement not reached\n`
This is result from Studio 12.5 accepting -Werr. I'll have a look at the pragmas

**Closed** 2016-08-24 09:14 UTC
Labels: 4.1, backport-review-4.1, bug, master, varnishd

**Comment by skrueger8** [comment] 2016-08-24 09:36
Ah indeed, I have removed `-Wall -Werror -Werror=unused-result` from `configure` but it somehow still sneaked in `VCC_CC = cc -m64 -O -g -Wall -Werror -Wno-error=unused-result -D_POSIX_PTHREAD_SEMANTICS -mt -Kpic -G -o %o %s`

Running `configure` with `VCC_CC='cc -m64 -O -g -D_POSIX_PTHREAD_SEMANTICS -mt -Kpic -G -o %o %s'` helped.

```
All 513 tests passed
```

Thanks again!

**Comment by Dridi** [comment] 2016-08-24 10:13
@nigoroll confirmed! :+1:

**Comment by hermunn** [comment] 2016-09-23 13:04
Backport review: Since this problem is limited to Solaris Studio, it will not be backported to 4.1.
