### ISSUE TITLE
storage allocation for varnish 5.2.1

### ISSUE THREAD

**Issue by hardik8585** [varnishcache/varnish-cache#2648] opened 2018-04-11 12:30 UTC
I tried to attach disk space for varnish 5.2.1 with 20 disks each of 8TB size (Total 160 TB). But it is taking only 17 disks(Total 136 TB).
Is there any limit in coding level or operation level that we can attach only that much size only ?

**Comment by gquintard** [comment] 2018-04-11 12:33
"it is taking only" <- how so, do you get an error or anything? Does it just ignore the remaining 3 disks? What is the command line you are using?

Please, send an email to varnish-misc before opening ticket, we'll be able to do a first analysis before.

**Comment by hermunn** [comment] 2018-04-12 07:35
This is the maximum virtual address space of your hardware kicking in; there are only 48 bits (not 64) available on the current Intel processors, and half of the space is reserved for the kernel. This gives you a maximum of 128 TiB for memory maps. See https://en.wikipedia.org/wiki/X86-64 for some more details on the matter.

This is not a bug in varnish, so I am closing this ticket.

If you can post the exact error message you get, then others who encounter this has a better chance of finding this page through search engines.

**Closed by hermunn** 2018-04-12 07:35 UTC
