### ISSUE TITLE
Varnish 4.1.3 issue

### ISSUE THREAD

**Issue by mwethington** [varnishcache/varnish-cache#2013] opened 2016-07-13 04:12 UTC
I am getting failures CLI on varnishadm backend.list after a couple hrs.

# varnishadm
200        
-----------------------------
Varnish Cache CLI 1.0
-----------------------------
Linux,3.16.0-4-amd64,x86_64,-junix,-smalloc,-smalloc,-hcritbit
varnish-4.1.3 revision 5e3b6d2

Type 'help' for command list.
Type 'quit' to close CLI session.

varnish> vcl.list
200        
PONG 1468383002 1.0
varnish> backend.list
200        
PONG 1468383008 1.0
varnish> 

## Expected Behavior
Show Sick or Healthy instances

## Current Behavior
Works for a couple hrs and stops.No idea why.

## Possible Solution
Restart every 2 hrs? service varnish reload does not help only "service varnish restart"

## env

Linux ip-10-248-9-248 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt11-1+deb8u6 (2015-11-09) x86_64 GNU/Linux

**Comment by lkarsten** [comment] 2016-07-13 08:05
Hi. Thanks for the report. I think this is a duplicate of #2010 , and to keep things tidy we'll do the followup there.

**Comment by gquintard** [comment] 2016-07-13 08:05
duplicate of #2010

**Closed by lkarsten** 2016-07-13 08:05 UTC
