### ISSUE TITLE
"varnishstat" not working as expected on varnish 5.0

### ISSUE THREAD

**Issue by shtihskar** [varnishcache/varnish-cache#2181] opened 2017-01-09 08:38 UTC
On varnish 5.0 running the following command gives:

```
root@32c5193cdf81:/home/src# varnishstat -1 -j -f MAIN.cache_hit     
{
  "timestamp": "2017-01-09T08:31:09",

}

```
No info related to MAIN.cache_hit is displayed. 
## Expected Behavior

```
root@32c5193cdf81:/home/src# varnishstat -1 -j -f MAIN.cache_hit     
{
  "timestamp": "2017-01-09T08:31:09",
 "MAIN.cache_hit": {
    "description": "Cache hits",
    "type": "MAIN", "flag": "c", "format": "i",
    "value": 9
  }
}

```

However the following command works as expected

```
root@32c5193cdf81:/home/src# varnishstat -1 -j -f MAIN.*        
{
  "timestamp": "2017-01-09T08:33:47",
  "MAIN.uptime": {
    "description": "Child process uptime",
    "type": "MAIN", "flag": "c", "format": "d",
    "value": 256608
  },
  "MAIN.sess_conn": {
    "description": "Sessions accepted",
    "type": "MAIN", "flag": "c", "format": "i",
    "value": 52865
  },
  "MAIN.sess_drop": {
    "description": "Sessions dropped",
    "type": "MAIN", "flag": "c", "format": "i",
    "value": 0
  },
  "MAIN.sess_fail": {
    "description": "Session accept failures",
    "type": "MAIN", "flag": "c", "format": "i",
    "value": 4
  },
  "MAIN.client_req_400": {
    "description": "Client requests received, subject to 400 errors",
    "type": "MAIN", "flag": "c", "format": "i",
    "value": 0
  },
  "MAIN.client_req_417": {
    "description": "Client requests received, subject to 417 errors",
    "type": "MAIN", "flag": "c", "format": "i",
    "value": 0
  },
  "MAIN.client_req": {
    "description": "Good client requests received",
    "type": "MAIN", "flag": "c", "format": "i",
    "value": 52865
  },
  "MAIN.cache_hit": {
    "description": "Cache hits",
    "type": "MAIN", "flag": "c", "format": "i",
    "value": 9
  },
  "MAIN.cache_hitpass": {
    "description": "Cache hits for pass",
    "type": "MAIN", "flag": "c", "format": "i",
    "value": 0
  },
  "MAIN.cache_miss": {
    "description": "Cache misses",
    "type": "MAIN", "flag": "c", "format": "i",
    "value": 52856
  },
  "MAIN.backend_conn": {
    "description": "Backend conn. success",
    "type": "MAIN", "flag": "c", "format": "i",
    "value": 0
  },
  "MAIN.backend_unhealthy": {
    "description": "Backend conn. not attempted",
    "type": "MAIN", "flag": "c", "format": "i",
    "value": 0
  },
  "MAIN.backend_busy": {
    "description": "Backend conn. too many",
    "type": "MAIN", "flag": "c", "format": "i",
    "value": 0
  },
  "MAIN.backend_fail": {
    "description": "Backend conn. failures",
    "type": "MAIN", "flag": "c", "format": "i",
    "value": 52859
  },
  "MAIN.backend_reuse": {
    "description": "Backend conn. reuses",
    "type": "MAIN", "flag": "c", "format": "i",
    "value": 0
  },
  "MAIN.backend_recycle": {
    "description": "Backend conn. recycles",
    "type": "MAIN", "flag": "c", "format": "i",
    "value": 0
  },
  "MAIN.backend_retry": {
    "description": "Backend conn. retry",
    "type": "MAIN", "flag": "c", "format": "i",
    "value": 0
  },
  "MAIN.fetch_head": {
    "description": "Fetch no body (HEAD)",
    "type": "MAIN", "flag": "c", "format": "i",
    "value": 0
  },
  "MAIN.fetch_length": {
    "description": "Fetch with Length",
    "type": "MAIN", "flag": "c", "format": "i",
    "value": 0
  },
   ....
}
```

Both commands (varnishstat -1 -j -f MAIN.cache_hit and varnishstat -1 -j -f MAIN.*)  work as expected on varnish 4.0

## Environment
I am running varnish 5.0 in a dockerised environment

Thank you,
Rakshith

**Comment by fgsch** [comment] 2017-01-09 11:42
Duplicate of #2118.

**Closed by fgsch** 2017-01-09 11:42 UTC

**Comment by hermunn** [comment] 2017-01-23 15:06
Backport review: Nothing commited, nothing to backport.
