### ISSUE TITLE
Assert error in Lck_CondWait(), cache/cache_lck.c line 203 (on Mac OS X)

### ISSUE THREAD

**Issue by bsdphk** [varnishcache/varnish-cache#1853] opened 2016-03-04 13:31 UTC
Old ticket imported from Trac
See archived copy here: https://varnish-cache.org/trac/ticket/1853

**Comment by nigoroll** [comment] 2016-06-16 10:43
@mjastrzebowski are you the original reporter of the (archived) ticket?

**Comment by nigoroll** [comment] 2016-06-16 11:08
The way I read the MacOS manpage, this should not be happening, also the panic trace provided shows that `errno==0` (because there is no `errno =` line present in the panic), so I'd say this smells like a macos bug.
Would you please try to reproduce on master (or at least a more current varnish version) and reopen if the issue still exists?

**Comment by lkarsten** [comment] 2016-06-27 14:58
Backport review: nothing commited.

**Comment by lkarsten** [comment] 2016-06-28 15:11
Got access to a osx instance now, and had to satisfy my curiosity.

On OSX pthread_cond_wait() can return non-null, the man page documents that EINVAL is a valid return code. There is no mention of errno being used, I think @nigoroll misread the man page on that point.

Discussed this a bit with Martin. Since this happens in VBT_Wait() this could be an issue with our kqueue waiter and/or tcp pools implementation.

It would require some effort to follow up on this, and since the original reporter has gone quiet and OSX is a nice-to-have platform, I think Nils did the right thing by closing it for now.

**Comment by yousefcisco** [comment] 2018-05-01 21:10
I'm consistently getting this error on a number of OSX machines. Is there any way I can help debug / get to the root of the issue?

**Comment by lkarsten** [comment] 2018-05-01 21:36
Reopened to get some fresh eyes on this. I'm not running Varnish on macos these days.

**Comment by winstonjz** [comment] 2018-05-01 23:38
@yousefcisco We are on the same MacOS as well I just noticed. Maybe the newest high sierra is not playing nice with Varnish.

**Comment by nigoroll** [comment] 2018-05-02 09:52
Thanks for the new panic infos. The original panic info did not have `errno = 22 (Invalid argument)` which I guess can be a helpful clue here.

**Comment by yousefcisco** [comment] 2018-05-02 16:01
I've downgraded my version of varnish and I'm still having the error. @nigoroll do you think this is a different issue?

**Comment by winstonjz** [comment] 2018-05-07 18:40
@nigoroll @yousefcisco I upgraded my version of varnish and I'm still getting the issue. 90% of my requests result in a 502 Gateway error through nginx

**Comment by winstonjz** [comment] 2018-05-23 21:54
@yousefcisco  I am still having major issues @nigoroll @fgsch  @bsdphk 
Our front end team is at a stand still. Is there any update on this issue?

**Comment by yousefcisco** [comment] 2018-05-24 12:09
Yeah we're still having this issue as well, some members on my team are thankfully on Sierra and don't have it. Everyone on High Sierra has it constantly.

@winstonjz I reduced the frequency of this issue by getting nginx to resolve static files instead of going through varnish which worked for the most part.

The other thing in common between all three panic errors (I think we need more) is the `do_stream` flag, could this be related? I'm gonna run a test with this flag set to false and see if that helps.

@fgsch @nigoroll can you shed some light on what `Lck_CondWait` does?

**Comment by nigoroll** [comment] 2018-05-24 12:14
`Lck_CondWait` wraps a condition variable wait. Apparently Apple has made a change which breaks our assumptions. @yousefcisco and @winstonjz it sounds like you might want to consider http://varnish-cache.org/business/index.html#business

**Comment by yousefcisco** [comment] 2018-05-24 12:45
@nigoroll My company is already with Fastly, would their professional services team be able to resolve this issue?

**Comment by nigoroll** [comment] 2018-05-24 13:58
@yousefcisco I cannot answer your question, I am not fastly.

**Comment by yousefcisco** [comment] 2018-05-27 11:46
@nigoroll I was just going to try and see if this issue happens without the `do_stream` flag as that's one thing I found in common between all three panic reports. It doesn't seem to be related though.

**Comment by bsdphk** [comment] 2018-06-13 06:41
Somebody needs to reproduce this and get at the core dump with a debugger to find out what is going on.

Alternatively they can stuff a bunch of VSL/printfs into their copy of the source-code.

The fact that we only see it on OS/X does not mean it's not a generic bug, any bug which can cause this would be very sensitive to both the implementation and scheduling of threads.

**Comment by bsdphk** [comment] 2019-04-23 08:07
Timing this one out

**Comment by lkarsten** [comment] 2019-08-19 10:34
This is still an issue on macos mojave 10.14.5, with git master:

```
[..]
**** s1   txresp|HTTP/1.1 200 OK\r
**** s1   txresp|Content-Length: 4\r
**** s1   txresp|\r
**** s1   txresp|foo1
**** s1   Loop #8
**   s1   === rxreq
---- s3   HTTP rx failed (fd:21 read: Connection reset by peer)
---- s2   HTTP rx failed (fd:20 read: Connection reset by peer)
---- s1   HTTP rx failed (fd:19 read: Connection reset by peer)
**** c1   rxhdrlen = 0
---- c1   HTTP header is incomplete
**** c3   rxhdrlen = 0
---- c3   HTTP header is incomplete
**** c2   rxhdrlen = 0
---- c2   HTTP header is incomplete
*    top  RESETTING after ./tests/b00048.vtc
**   c2   Waiting for client
**   c3   Waiting for client
***  v1   debug|Error: Child (36250) died signal=6
**   s0   Waiting for server (4/-1)
**   s1   Waiting for server (-1/19)
**   s2   Waiting for server (-1/20)
**   s3   Waiting for server (-1/21)
**   v1   Wait
**** v1   CLI TX|panic.clear
**** dT   0.716
***  v1   debug|Error: Child (36250) Panic at: Mon, 19 Aug 2019 10:09:52 GMT
***  v1   debug|Assert error in Lck_CondWait(), cache/cache_lck.c line 218:
***  v1   debug|  Condition(errno == 0 || errno == ETIMEDOUT || errno == EINTR) not true.
***  v1   debug|version = varnish-trunk revision f4dcf8f02a2fb059dacba4c7bedefccbe9897cd2, vrt api = 9.0
***  v1   debug|ident = Darwin,18.6.0,x86_64,-jnone,-sdefault,-sdefault,-hcritbit,poll
***  v1   debug|now = 87406.039956 (mono), 1566209392.873826 (real)
***  v1   debug|Backtrace:
***  v1   debug|  0x107835171: 0   varnishd                            0x0000000107835171 pan_backtrace + 49
***  v1   debug|  0x107834f50: 0   varnishd                            0x0000000107834f50 pan_ic + 688
***  v1   debug|  0x1078ea4d5: 0   varnishd                            0x00000001078ea4d5 VAS_Fail + 85
***  v1   debug|  0x10782e67b: 0   varnishd                            0x000000010782e67b Lck_CondWait + 699
***  v1   debug|  0x10784b695: 0   varnishd                            0x000000010784b695 VCP_Wait + 565
***  v1   debug|  0x10784b457: 0   varnishd                            0x000000010784b457 VTP_Wait + 39
***  v1   debug|  0x1077fb6b0: 0   varnishd                            0x0000000107
***  v1   debug|7fb6b0 vbe_dir_gethdrs + 1072
***  v1   debug|  0x10780a130: 0   varnishd                            0x000000010780a130 VDI_GetHdr + 416
***  v1   debug|  0x107818640: 0   varnishd                            0x0000000107818640 vbf_stp_startfetch + 1024
***  v1   debug|  0x1078172c6: 0   varnishd                            0x00000001078172c6 vbf_fetch_thread + 1638
***  v1   debug|errno = 22 (Invalid argument)
***  v1   debug|thread = (cache-worker)
***  v1   debug|thr.req = 0x0 {
***  v1   debug|},
***  v1   debug|thr.busyobj = 0x107f7e020 {
***  v1   debug|  end = 0x107f8e000,
***  v1   debug|  retries = 0,
***  v1   debug|  sp = 0x7f8abcc070f0 {
***  v1   debug|    fd = 26, vxid = 1001,
***  v1   debug|    t_open = 1566209392.659656,
***  v1   debug|    t_idle = 1566209392.873595,
***  v1   debug|    ws = 0x7f8abcc07130 {
***  v1   debug|      id = \"ses\",
***  v1   debug|      {s, f, r, e} = {0x7f8abcc07170, +96, 0x0, +344},
***  v1   debug|    },
***  v1   debug|    transport = HTTP/1 {
***  v1   debug|      state = HTTP1::Proc
***  v1   debug|    }
***  v1   debug|    client = 127.0.0.1 57489 127.0.0.1:57477,
***  v1   debug|  },
***  v1   debug|  worker = 0x700003d21df0 {
***  v1   debug|    ws = 0x700003d21e98 {
***  v1   debug|      id = \"wrk\",
***  v1   debug|      {s, f, r, e} = {0x700003d213e0, +0, 0x0, +2040},
***  v1   debug|    },
***  v1   debug|    VCL::method = BACKEND_FETCH,
***  v1   debug|    VCL::return = fetch,
***  v1   debug|    VCL::methods = {BACKEND_FETCH},
***  v1   debug|  },
***  v1   debug|
***  v1   debug|vfc = 0x107f7ff20 {
***  v1   debug|    failed = 0,
***  v1   debug|    req = 0x107f7e630,
***  v1   debug|    resp = 0x107f7eaa8,
***  v1   debug|    wrk = 0x700003d21df0,
***  v1   debug|    oc = 0x7f8abcd02bc0,
***  v1   debug|    obj_flags = 0x0,
***  v1   debug|  },
***  v1   debug|  ws = 0x107f7e060 {
***  v1   debug|    id = \"bo\",
***  v1   debug|    {s, f, r, e} = {0x107f7ff68, +192, 0x0, +57488},
***  v1   debug|  },
***  v1   debug|  ws_bo = 0x107f7ffb8,
***  v1   debug|  http[bereq] = 0x107f7e630 {
***  v1   debug|    ws = 0x107f7e060 {
***  v1   debug|      [Already dumped, see above]
***  v1   debug|    },
***  v1   debug|    hdrs {
***  v1   debug|      \"GET\",
***  v1   debug|      \"/c1\",
***  v1   debug|      \"HTTP/1.1\",
***  v1   debug|      \"Host: 127.0.0.1\",
***  v1   debug|      \"X-Forwarded-For: 127.0.0.1\",
***  v1   debug|      \"X-Varnish: 1044\",
***  v1   debug|    },
***  v1   debug|  },
***  v1   debug|  http[beresp] = 0x107f7eaa8 {
***  v1   debug|    ws = 0x107f7e060 {
***  v1   debug|      [Already dumped, see above]
***  v1   debug|    },
***  v1   debug|    hdrs {
***  v1   debug|    },
***  v1   debug|  },
***  v1   debug|  objcore[fetch] = 0x7f8abcd02bc0 {
***  v1   debug|    refcnt = 2,
***  v1   debug|    flags = {busy, private},
***  v1   debug|    exp_flags = {},
***  v1   debug|    boc = 0x7f8abcd029e0 {
***  v1   debug|      refcnt = 2,
***  v1   debug|      state = req_done,
***  v1   debug|      vary = 0x0,
***  v1   debug|      stevedore_priv = 0x0,
***  v1   debug|    },
***  v1   debug|    exp = {0.000000, 0.000000, 0.000000, 0.000000},
***  v1   debug|    objhead = 0x7f8abcc05d00,
***  v1   debug|    stevedore = 0x0,
***  v1   debug|  },
***  v1   debug|  http_conn = 0x107f7ffc8 {
***  v1   debug|    fd =
***  v1   debug| 27 (@0x7f8abce013b4),
***  v1   debug|    doclose = NULL,
***  v1   debug|    ws = 0x0 {
***  v1   debug|    },
***  v1   debug|    {rxbuf_b, rxbuf_e} = {0x0, 0x0},
***  v1   debug|    {pipeline_b, pipeline_e} = {0x0, 0x0},
***  v1   debug|    content_length = 0,
***  v1   debug|    body_status = none,
***  v1   debug|    first_byte_timeout = 60.000000,
***  v1   debug|    between_bytes_timeout = 60.000000,
***  v1   debug|  },
***  v1   debug|  flags = {do_stream, do_pass, uncacheable},
***  v1   debug|  director_req = 0x7f8abcd01f20 {
***  v1   debug|    cli_name = vcl1.s0,
***  v1   debug|    admin_health = healthy, changed = 1566209392.557024,
***  v1   debug|    type = backend {
***  v1   debug|      ipv4 = 127.0.0.1,
***  v1   debug|      port = 57471,
***  v1   debug|      hosthdr = 127.0.0.1,
***  v1   debug|      n_conn = 3,
***  v1   debug|    },
***  v1   debug|  },
***  v1   debug|  director_resp = director_req,
***  v1   debug|  vcl = {
***  v1   debug|    name = \"vcl1\",
***  v1   debug|    busy = 6,
***  v1   debug|    discard = 0,
***  v1   debug|    state = auto,
***  v1   debug|    temp = warm,
***  v1   debug|    conf = {
***  v1   debug|      syntax = \"41\",
***  v1   debug|      srcname = {
***  v1   debug|        \"<vcl.inline>\",
***  v1   debug|        \"Builtin\",
***  v1   debug|      },
***  v1   debug|    },
***  v1   debug|  },
***  v1   debug|},
***  v1   debug|vmods = {
***  v1   debug|},
***  v1   debug|
***  v1   debug|
***  v1   debug|Debug: Child cleanup complete
***  v1   CLI RX  200
---- v1   Unexpected panic
*    top  failure during reset
#    top  TEST ./tests/b00048.vtc FAILED (0.718) exit=2
FAIL tests/b00048.vtc (exit status: 2)
```

The following test cases are failing:

```
lkarsten@jungel:~/work/Varnish-Cache/bin/varnishtest$ grep ^FAIL\  test-suite.log
FAIL tests/b00048.vtc (exit status: 2)
FAIL tests/c00019.vtc (exit status: 2)
FAIL tests/c00025.vtc (exit status: 2)
FAIL tests/c00027.vtc (exit status: 2)
FAIL tests/c00045.vtc (exit status: 2)
FAIL tests/d00002.vtc (exit status: 2)
FAIL tests/d00003.vtc (exit status: 2)
FAIL tests/r00425.vtc (exit status: 2)
FAIL tests/r00861.vtc (exit status: 2)
FAIL tests/r00961.vtc (exit status: 2)
FAIL tests/r01030.vtc (exit status: 2)
FAIL tests/r01120.vtc (exit status: 2)
FAIL tests/r01168.vtc (exit status: 2)
FAIL tests/r01781.vtc (exit status: 2)
FAIL tests/r02372.vtc (exit status: 2)
FAIL tests/r02700.vtc (exit status: 2)
FAIL tests/v00050.vtc (exit status: 2)
```

**Comment by bsdphk** [comment] 2019-08-22 07:44
I have added an assert on the ts_nsec field to make sure it is valid.

I'm pretty sure we're not guilty of this one: https://wiki.sei.cmu.edu/confluence/pages/viewpage.action?pageId=87151984 but that is probably my best guess by now.

**Comment by lkarsten** [comment] 2019-08-22 08:07
Hi.

Re-ran with latest master now, I'm afraid it is the same assert that is triggering:

```
lkarsten@jungel:~/work/Varnish-Cache$ grep Assert bin/varnishtest/test-suite.log
***  v1   debug|Assert error in Lck_CondWait(), cache/cache_lck.c line 219:
***  v1   debug|Assert error in Lck_CondWait(), cache/cache_lck.c line 219:
***  v1   debug|Assert error in Lck_CondWait(), cache/cache_lck.c line 219:
***  v1   debug|Assert error in Lck_CondWait(), cache/cache_lck.c line 219:
***  v1   debug|Assert error in Lck_CondWait(), cache/cache_lck.c line 219:
***  v1   debug|Assert error in Lck_CondWait(), cache/cache_lck.c line 219:
***  v1   debug|Assert error in Lck_CondWait(), cache/cache_lck.c line 219:
***  v1   debug|Assert error in Lck_CondWait(), cache/cache_lck.c line 219:
***  v1   debug|Assert error in Lck_CondWait(), cache/cache_lck.c line 219:
***  v1   debug|Assert error in Lck_CondWait(), cache/cache_lck.c line 219:
***  v1   debug|Assert error in Lck_CondWait(), cache/cache_lck.c line 219:
***  v1   debug|Assert error in Lck_CondWait(), cache/cache_lck.c line 219:
***  v1   debug|Assert error in Lck_CondWait(), cache/cache_lck.c line 219:
lkarsten@jungel:~/work/Varnish-Cache$ grep Assert bin/varnishtest/test-suite.log  | wc -l
      13
```

```
lkarsten@jungel:~/work/Varnish-Cache$ grep ^FAIL\   bin/varnishtest/test-suite.log | sort
FAIL tests/c00004.vtc (exit status: 2)
FAIL tests/c00045.vtc (exit status: 2)
FAIL tests/c00060.vtc (exit status: 2)
FAIL tests/c00072.vtc (exit status: 2)
FAIL tests/d00002.vtc (exit status: 2)
FAIL tests/d00003.vtc (exit status: 2)
FAIL tests/e00017.vtc (exit status: 2)
FAIL tests/r00425.vtc (exit status: 2)
FAIL tests/r02042.vtc (exit status: 2)
FAIL tests/r02219.vtc (exit status: 2)
FAIL tests/r02372.vtc (exit status: 2)
FAIL tests/r03006.vtc (exit status: 2)
FAIL tests/v00043.vtc (exit status: 2)
```

b00048.vtc didn't fail this time. Pasting backtrace from c00004.vtc, in case you/someone can spot something different this time around:

```
**** v1   CLI TX|panic.clear
***  v1   debug|Error: Child (14361) died signal=6
**** dT   0.546
***  v1   debug|Error: Child (14361) Panic at: Thu, 22 Aug 2019 07:50:26 GMT
***  v1   debug|Assert error in Lck_CondWait(), cache/cache_lck.c line 219:
***  v1   debug|  Condition(errno == 0 || errno == ETIMEDOUT || errno == EINTR) not true.
***  v1   debug|version = varnish-trunk revision eed8289377394440c6c111f431f031735485d5ac, vrt api = 9.0
***  v1   debug|ident = Darwin,18.6.0,x86_64,-jnone,-sdefault,-sdefault,-hcritbit,kqueue
***  v1   debug|now = 338240.331741 (mono), 1566460226.563716 (real)
***  v1   debug|Backtrace:
***  v1   debug|  0x10340a0a1: 0   varnishd                            0x000000010340a0a1 pan_backtrace + 49
***  v1   debug|  0x103409e80: 0   varnishd                            0x0000000103409e80 pan_ic + 688
***  v1   debug|  0x1034bf4a5: 0   varnishd                            0x00000001034bf4a5 VAS_Fail + 85
***  v1   debug|  0x1034035ae: 0   varnishd                            0x00000001034035ae Lck_CondWait + 766
***  v1   debug|  0x1034205c5: 0   varnishd                            0x00000001034205c5 VCP_Wait + 565
***  v1   debug|  0x103420387: 0   varnishd                            0x0000000103420387 VTP_Wait + 39
***  v1   debug|  0x1033d05a0: 0   varnishd                            0x0000000
***  v1   debug|1033d05a0 vbe_dir_gethdrs + 1072
***  v1   debug|  0x1033df020: 0   varnishd                            0x00000001033df020 VDI_GetHdr + 416
***  v1   debug|  0x1033ed530: 0   varnishd                            0x00000001033ed530 vbf_stp_startfetch + 1024
***  v1   debug|  0x1033ec1b6: 0   varnishd                            0x00000001033ec1b6 vbf_fetch_thread + 1638
***  v1   debug|errno = 22 (Invalid argument)
***  v1   debug|thread = (cache-worker)
***  v1   debug|thr.req = 0x0 {
***  v1   debug|},
***  v1   debug|thr.busyobj = 0x103b23020 {
***  v1   debug|  end = 0x103b33000,
***  v1   debug|  retries = 0,
***  v1   debug|  sp = 0x7ffa6bf02050 {
***  v1   debug|    fd = 26, vxid = 1000,
***  v1   debug|    t_open = 1566460226.537500,
***  v1   debug|    t_idle = 1566460226.563487,
***  v1   debug|    ws = 0x7ffa6bf02090 {
***  v1   debug|      id = \"ses\",
***  v1   debug|      {s, f, r, e} = {0x7ffa6bf020d0, +96, 0x0, +344},
***  v1   debug|    },
***  v1   debug|    transport = HTTP/1 {
***  v1   debug|      state = HTTP1::Proc
***  v1   debug|    }
***  v1   debug|    client = 127.0.0.1 63370 127.0.0.1:63349,
***  v1   debug|  },
***  v1   debug|  worker = 0x700002f4cdf0 {
***  v1   debug|    ws = 0x700002f4ce98 {
***  v1   debug|      id = \"wrk\",
***  v1   debug|      {s, f, r, e} = {0x700002f4c3e0, +0, 0x0, +2040},
***  v1   debug|    },
***  v1   debug|    VCL::method = BACKEND_FETCH,
***  v1   debug|    VCL::return = fetch,
***  v1   debug|    VCL::methods = {BACKEND_FETCH},
***  v1   debug|  },
***  v1   debug|
***  v1   debug|  vfc = 0x103b24f20 {
***  v1   debug|    failed = 0,
***  v1   debug|    req = 0x103b23630,
***  v1   debug|    resp = 0x103b23aa8,
***  v1   debug|    wrk = 0x700002f4cdf0,
***  v1   debug|    oc = 0x7ffa6bf027d0,
***  v1   debug|    obj_flags = 0x0,
***  v1   debug|  },
***  v1   debug|  ws = 0x103b23060 {
***  v1   debug|    id = \"bo\",
***  v1   debug|    {s, f, r, e} = {0x103b24f68, +232, 0x0, +57488},
***  v1   debug|  },
***  v1   debug|  ws_bo = 0x103b24fe0,
***  v1   debug|  http[bereq] = 0x103b23630 {
***  v1   debug|    ws = 0x103b23060 {
***  v1   debug|      [Already dumped, see above]
***  v1   debug|    },
***  v1   debug|    hdrs {
***  v1   debug|      \"GET\",
***  v1   debug|      \"/\",
***  v1   debug|      \"HTTP/1.1\",
***  v1   debug|      \"Foobar: 3\",
***  v1   debug|      \"Host: 127.0.0.1\",
***  v1   debug|      \"X-Forwarded-For: 127.0.0.1\",
***  v1   debug|      \"Accept-Encoding: gzip\",
***  v1   debug|      \"X-Varnish: 1006\",
***  v1   debug|    },
***  v1   debug|  },
***  v1   debug|  http[beresp] = 0x103b23aa8 {
***  v1   debug|    ws = 0x103b23060 {
***  v1   debug|      [Already dumped, see above]
***  v1   debug|    },
***  v1   debug|    hdrs {
***  v1   debug|    },
***  v1   debug|  },
***  v1   debug|  objcore[fetch] = 0x7ffa6bf027d0 {
***  v1   debug|    refcnt = 2,
***  v1   debug|    flags = {busy},
***  v1   debug|    exp_flags = {},
***  v1   debug|    boc = 0x7ffa6bf02880 {
***  v1   debug|      refcnt = 2,
***  v1   debug|      state = req_done,
***  v1   debug|      vary = 0x7ffa6bd034b0,
***  v1   debug|      stevedore_priv = 0x0,
***  v1   debug|    },
***  v1   debug|    exp = {0.000000, 0.000000, 0.000000, 0.000000},
***  v1   debug|    objhead = 0x7ffa6bf02570,
***  v1   debug|    s
***  v1   debug|tevedore = 0x0,
***  v1   debug|  },
***  v1   debug|  http_conn = 0x103b24ff0 {
***  v1   debug|    fd = 27 (@0x7ffa6be01d34),
***  v1   debug|    doclose = NULL,
***  v1   debug|    ws = 0x0 {
***  v1   debug|    },
***  v1   debug|    {rxbuf_b, rxbuf_e} = {0x0, 0x0},
***  v1   debug|    {pipeline_b, pipeline_e} = {0x0, 0x0},
***  v1   debug|    content_length = 0,
***  v1   debug|    body_status = none,
***  v1   debug|    first_byte_timeout = 60.000000,
***  v1   debug|    between_bytes_timeout = 60.000000,
***  v1   debug|  },
***  v1   debug|  flags = {do_stream},
***  v1   debug|  director_req = 0x7ffa6bd03ba0 {
***  v1   debug|    cli_name = vcl1.s1,
***  v1   debug|    admin_health = healthy, changed = 1566460226.434659,
***  v1   debug|    type = backend {
***  v1   debug|      ipv4 = 127.0.0.1,
***  v1   debug|      port = 63347,
***  v1   debug|      hosthdr = 127.0.0.1,
***  v1   debug|      n_conn = 1,
***  v1   debug|    },
***  v1   debug|  },
***  v1   debug|  director_resp = director_req,
***  v1   debug|  vcl = {
***  v1   debug|    name = \"vcl1\",
***  v1   debug|    busy = 2,
***  v1   debug|    discard = 0,
***  v1   debug|    state = auto,
***  v1   debug|    temp = warm,
***  v1   debug|    conf = {
***  v1   debug|      syntax = \"41\",
***  v1   debug|      srcname = {
***  v1   debug|        \"<vcl.inline>\",
***  v1   debug|        \"Builtin\",
***  v1   debug|      },
***  v1   debug|    },
***  v1   debug|  },
***  v1   debug|},
***  v1   debug|vmods = {
***  v1   debug|},
***  v1   debug|
***  v1   debug|
**** dT   0.547
***  v1   debug|Debug: Child cleanup complete
***  v1   CLI RX  200
---- v1   Unexpected panic
*    top  failure during reset
#    top  TEST ./tests/c00004.vtc FAILED (0.548) exit=2
FAIL tests/c00004.vtc (exit status: 2)

```

**Comment by lkarsten** [comment] 2019-11-11 08:38
Re-running with current master, on macos mojave 10.14.5, the problem is still there.

There may be value in checking this on macos catalina/10.15.0, but that is still breaking lots of apps around so I haven't upgraded.

Tests that fail are: b00013 b00035 b00048 c00008 c00027 d00002 e00026 e00031 g00007 r00476 r00612 r00984 r01038 r01123 r01442 r01637 r01764 r02372 s00000 

Sample from failing c00008.vtc:
```
***  v1   debug|Error: Child (17426) Panic at: Mon, 11 Nov 2019 08:12:42 GMT
***  v1   debug|Assert error in Lck_CondWait(), cache/cache_lck.c line 219:
***  v1   debug|  Condition(errno == 0 || errno == ETIMEDOUT || errno == EINTR) not true.
***  v1   debug|version = varnish-trunk revision 0496921fea70bb6470c52082efb520cf9a2cf3d1, vrt api = 10.0
***  v1   debug|ident = Darwin,18.6.0,x86_64,-jnone,-sdefault,-sdefault,-hcritbit,kqueue
***  v1   debug|now = 585967.780047 (mono), 1573459962.869593 (real)
***  v1   debug|Backtrace:
***  v1   debug|  0x1082c6b71: 0   varnishd                            0x00000001082c6b71 pan_backtrace + 49
***  v1   debug|  0x1082c6950: 0   varnishd                            0x00000001082c6950 pan_ic + 688
***  v1   debug|  0x10837c1b5: 0   varnishd                            0x000000010837c1b5 VAS_Fail + 85
***  v1   debug|  0x1082c002e: 0   varnishd                            0x00000001082c002e Lck_CondWait + 766
***  v1   debug|  0x1082dd385: 0   varnishd                            0x00000001082dd385 VCP_Wait + 565
***  v1   debug|  0x1082dd147: 0   varnishd                            0x00000001082dd147 VTP_Wait + 39
***  v1   debug|  0x10828ccc0: 0   varnishd                            0x000000
***  v1   debug|010828ccc0 vbe_dir_gethdrs + 1072
***  v1   debug|  0x10829b710: 0   varnishd                            0x000000010829b710 VDI_GetHdr + 416
***  v1   debug|  0x1082a9e80: 0   varnishd                            0x00000001082a9e80 vbf_stp_startfetch + 1024
***  v1   debug|  0x1082a8b16: 0   varnishd                            0x00000001082a8b16 vbf_fetch_thread + 1638
***  v1   debug|errno = 22 (Invalid argument)
***  v1   debug|thread = (cache-worker)
***  v1   debug|thr.req = 0x0 {
***  v1   debug|},
***  v1   debug|thr.busyobj = 0x1089e3020 {
***  v1   debug|  end = 0x1089f3000,
***  v1   debug|  retries = 0,
***  v1   debug|  sp = 0x7fe9b0e02830 {
***  v1   debug|    fd = 23, vxid = 1000,
***  v1   debug|    t_open = 1573459962.852305,
***  v1   debug|    t_idle = 1573459962.868538,
***  v1   debug|    ws = 0x7fe9b0e02870 {
***  v1   debug|      id = \"ses\",
***  v1   debug|      {s, f, r, e} = {0x7fe9b0e028b0, +96, 0x0, +344},
***  v1   debug|    },
***  v1   debug|    transport = HTTP/1 {
***  v1   debug|      state = HTTP1::Proc
***  v1   debug|    }
***  v1   debug|    client = 127.0.0.1 55194 127.0.0.1:55179,
***  v1   debug|  },
***  v1   debug|  worker = 0x70000d1a6df0 {
***  v1   debug|    ws = 0x70000d1a6e98 {
***  v1   debug|      id = \"wrk\",
***  v1   debug|      {s, f, r, e} = {0x70000d1a63e0, +0, 0x0, +2040},
***  v1   debug|    },
***  v1   debug|    VCL::method = BACKEND_FETCH,
***  v1   debug|    VCL::return = 0x0,
***  v1   debug|    VCL::methods = {BACKEND_FETCH},
***  v1   debug|  },
***  v1   debug|  vfc = 0x1089e4f18 {
***  v1   debug|    failed = 0,
***  v1   debug|    req = 0x1089e3628,
***  v1   debug|    resp = 0x1089e3aa0,
***  v1   debug|    wrk = 0x70000d1a6df0,
***  v1   debug|    oc = 0x7fe9b0f00fa0,
***  v1   debug|    obj_flags = 0x0,
***  v1   debug|  },
***  v1   debug|  ws = 0x1089e3060 {
***  v1   debug|    id = \"bo\",
***  v1   debug|    {s, f, r, e} = {0x1089e4f60, +216, 0x0, +57496},
***  v1   debug|  },
***  v1   debug|  ws_bo = 0x1089e4fc8,
***  v1   debug|  http[bereq] = 0x1089e3628 {
***  v1   debug|    ws = 0x1089e3060 {
***  v1   debug|      [Already dumped, see above]
***  v1   debug|    },
***  v1   debug|    hdrs {
***  v1   debug|      \"GET\",
***  v1   debug|      \"/bar\",
***  v1   debug|      \"HTTP/1.1\",
***  v1   debug|      \"X-Forwarded-For: 127.0.0.1\",
***  v1   debug|      \"host: 127.0.0.1\",
***  v1   debug|      \"Accept-Encoding: gzip\",
***  v1   debug|      \"X-Varnish: 1007\",
***  v1   debug|    },
***  v1   debug|  },
***  v1   debug|  http[beresp] = 0x1089e3aa0 {
***  v1   debug|    ws = 0x1089e3060 {
***  v1   debug|      [Already dumped, see above]
***  v1   debug|    },
***  v1   debug|    hdrs {
***  v1   debug|    },
***  v1   debug|  },
***  v1   debug|  objcore[fetch] = 0x7fe9b0f00fa0 {
***  v1   debug|    refcnt = 2,
***  v1   debug|    flags = {busy},
***  v1   debug|    exp_flags = {},
***  v1   debug|    boc = 0x7fe9b0f00df0 {
***  v1   debug|      refcnt = 2,
***  v1   debug|      state = req_done,
***  v1   debug|      vary = 0x0,
***  v1   debug|      stevedore_priv = 0x0,
***  v1   debug|    },
***  v1   debug|    exp = {0.000000, 0.000000, 0.000000, 0.000000},
***  v1   debug|    objhead = 0x7fe9b0f008d0,
***  v1   debug|    stevedore = 0x0,
***  v1   debug|  },
***  v1   debug|  http_co
***  v1   debug|nn = 0x1089e4fd8 {
***  v1   debug|    fd = 27 (@0x7fe9b0d04a94),
***  v1   debug|    doclose = NULL,
***  v1   debug|    ws = 0x0 {
***  v1   debug|    },
***  v1   debug|    {rxbuf_b, rxbuf_e} = {0x0, 0x0},
***  v1   debug|    {pipeline_b, pipeline_e} = {0x0, 0x0},
***  v1   debug|    content_length = 0,
***  v1   debug|    body_status = none,
***  v1   debug|    first_byte_timeout = 60.000000,
***  v1   debug|    between_bytes_timeout = 60.000000,
***  v1   debug|  },
***  v1   debug|  flags = {do_stream},
***  v1   debug|  director_req = 0x7fe9b0d044b0 {
***  v1   debug|    cli_name = vcl1.s1,
***  v1   debug|    admin_health = healthy, changed = 1573459962.750314,
***  v1   debug|    type = backend {
***  v1   debug|      ipv4 = 127.0.0.1,
***  v1   debug|      port = 55174,
***  v1   debug|      hosthdr = 127.0.0.1,
***  v1   debug|      n_conn = 1,
***  v1   debug|    },
***  v1   debug|  },
***  v1   debug|  director_resp = director_req,
***  v1   debug|  vcl = {
***  v1   debug|    name = \"vcl1\",
***  v1   debug|    busy = 2,
***  v1   debug|    discard = 0,
***  v1   debug|    state = auto,
***  v1   debug|    temp = warm,
***  v1   debug|    conf = {
***  v1   debug|      syntax = \"41\",
***  v1   debug|      srcname = {
***  v1   debug|        \"<vcl.inline>\",
***  v1   debug|        \"Builtin\",
***  v1   debug|      },
***  v1   debug|    },
***  v1   debug|  },
***  v1   debug|},
***  v1   debug|vmods = {
***  v1   debug|},
***  v1   debug|
***  v1   debug|Debug: Child cleanup complete
```
```

**Comment by nigoroll** [comment] 2020-01-15 09:17
pow-wow: will have another look

**Comment by nigoroll** [comment] 2020-01-15 12:09
FYI: https://opensource.apple.com/source/libpthread/libpthread-330.250.2/src/pthread_cond.c.auto.html (still need to check with enough time)

**Closed** 2020-01-20 13:31 UTC
Labels: a=help wanted

**Comment by nigoroll** [comment] 2020-01-21 14:05
can anyone confirm that the issue is in fact fixed?
I have spent some time with someone inside apple to reproduce it and failed so far, but I also still do not have on own dev environment on macos.

**Comment by gquintard** [comment] 2020-01-21 15:48
is the travis setup helpful here?

**Comment by nigoroll** [comment] 2020-01-21 17:05
travis is helpful, but I checked the builds before and after e5e545f and saw no difference.
