### ISSUE TITLE
Assert error in VTCP_check_hup(), vtcp.c line 551:   Condition(sock > 0) not true

### ISSUE THREAD

**Issue by nigoroll** [varnishcache/varnish-cache#2180] opened 2017-01-07 11:58 UTC
```
Panic at: Thu, 08 Dec 2016 18:10:46 GMT
"Assert error in VTCP_check_hup(), vtcp.c line 551:
  Condition(sock > 0) not true.
thread = (cache-worker)
version = varnish-5.0.0 revision 4eee5c4
ident = Linux,2.6.32-504.8.1.el6.x86_64,x86_64,-junix,-smalloc,-smalloc,-hcritbit,epoll
Backtrace:
  0x434313: pan_ic+0x163
  0x7fb3dbb350f9: libvarnish.so(+0xf0f9) [0x7fb3dbb350f9]
  0x454548: HTTP1_Session+0x468
  0x454da7: http1_req+0x57
  0x44c4e5: WRK_Thread+0x495
  0x44c91b: pool_thread+0x2b
  0x38c8e07aa1: libpthread.so.0() [0x38c8e07aa1]
  0x38c8ae893d: libc.so.6(clone+0x6d) [0x38c8ae893d]
req = 0x7faefda5b020 {
  vxid = 25809176, transport = HTTP/1 {
    state = HTTP1::Busy
  }
  step = R_STP_LOOKUP,
  req_body = R_BODY_NONE,
  restarts = 0, esi_level = 0,
  sp = 0x7fb022bda020 {
    fd = 0, vxid = 25809175,
    t_open = 1481220645.163754,
    t_idle = 1481220645.163754,
    transport = HTTP/1 {
      state = HTTP1::Busy
    }
client = 127.0.0.1 40184,
  },
  ws = 0x7faefda5b1f8 {
    id = \"req\",
    {s, f, r, e} = {0x7faefda5d658, +2968, +55712, +55712},
  },
  http_conn = 0x7faefda5b128 {
    fd = 0,
    doclose = NULL,
    ws = 0x7faefda5b1f8,
    {rxbuf_b, rxbuf_e} = {0x7faefda5d9a0, 0x7faefda5dcc8},
    {pipeline_b, pipeline_e} = {(nil), (nil)},
    content_length = -1,
    body_status = none,
    first_byte_timeout = 0.000000,
    between_bytes_timeout = 0.000000,
  },
  http[req] = 0x7faefda5b290 {
    ws[req] = 0x7faefda5b1f8,
    hdrs {
      \"GET\",
      \"/\",
      \"HTTP/1.1\",
      *REDACTED*,
    },
  },
  vcl = {
    name = \"vcl_20161208143033\"
    busy = 69
    discard = 0,
    state = auto,
    temp = warm,
    conf = {
      srcname = {
      *REDACTED*,
      },
    },
  },
  flags = {
  },
},

"
```

**Comment by nigoroll** [comment] 2017-01-09 12:11
Also smells as possibly related to #2117

**Comment by bsdphk** [comment] 2017-01-30 11:46
Yes, both this and #2117 have sp->fd == 0.

Closing this, will track that issue on 2117 only

**Closed by bsdphk** 2017-01-30 11:46 UTC

**Comment by hermunn** [comment] 2017-02-06 11:47
Backport review: Duplicate of #2117, nothing to backport here.
