### ISSUE TITLE
Varnish doesn't like long vcl+backend names

### ISSUE THREAD

**Issue by gquintard** [varnishcache/varnish-cache#2157] opened 2016-12-08 15:36 UTC
There are some checks to avoid too long names, but counters are a concatenation of the two and this is isn't protected, allowing to get this panic:

```
***  v1    0.7 debug| Error: Child (6535) died signal=6 (core dumped)\n
***  v1    0.7 debug| Error: Child (6535) Panic at: Thu, 08 Dec 2016 15:31:10 GMT\n
***  v1    0.7 debug| "Assert error in VSM_common_alloc(), common/common_vsm.c line 212:\n
***  v1    0.7 debug|   Condition(strlen(ident) < sizeof(vr->chunk->ident)) not true.\n
***  v1    0.7 debug| thread = (cache-main)\n
***  v1    0.7 debug| version = varnish-5.0.0 revision 99d036f\n
***  v1    0.7 debug| ident = Linux,4.8.11-1-ARCH,x86_64,-jnone,-smalloc,-smalloc,-hcritbit,epoll\n
***  v1    0.7 debug| Backtrace:\n
***  v1    0.7 debug|   0x4353b5: varnishd() [0x4353b5]\n
***  v1    0.7 debug|   0x44f310: varnishd(VSM_common_alloc+0x390) [0x44f310]\n
***  v1    0.7 debug|   0x43ec3a: varnishd(VSM_Alloc+0x3a) [0x43ec3a]\n
***  v1    0.7 debug|   0x415bed: varnishd(VBE_Event+0x6d) [0x415bed]\n
***  v1    0.7 debug|   0x4400aa: varnishd() [0x4400aa]\n
***  v1    0.7 debug|   0x440490: varnishd() [0x440490]\n
***  v1    0.7 debug|   0x4417db: varnishd() [0x4417db]\n
***  v1    0.7 debug|   0x7f5132f7ff9a: libvarnish.so(+0x7f9a) [0x7f5132f7ff9a]\n
***  v1    0.7 debug|   0x7f5132f8031f: libvarnish.so(+0x831f) [0x7f5132f8031f]\n
***  v1    0.7 debug|   0x7f5132f82af0: libvarnish.so(VLU_Fd+0xd0) [0x7f5132f82af0]\n
***  v1    0.7 debug| \n
***  v1    0.7 debug| "\n

```

## VTC
```
varnishtest "Long vcl/backend names"

server s1 {
	rxreq
	txresp
} -start

varnish v1 -vcl+backend {} -start

# 64 chars vlc name, 64 chars backend name
varnish v1 -cliok { vcl.inline abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789 "vcl 4.0; backend abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789 {.host = \"127.0.0.1\"; .port = \"${s1_port}\";} " }

# 127 chars vlc name, 1 char backend name
varnish v1 -cliok { vcl.inline abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef012345678 "vcl 4.0; backend a {.host = \"127.0.0.1\"; .port = \"${s1_port}\";} " }

client c1 {
	txreq
	rxresp
} -run
```
## Current Behavior
Clean error at least.

## Context
This is on master and affects 5.0 and 4.x too.

**Comment by nigoroll** [comment] 2016-12-08 15:45
seeing the same, but did not get around documenting it. Thanks you

**Comment by bsdphk** [comment] 2016-12-09 10:08
Given that we live in an age of buffer-overflows, the right defensive action might be to hard-limit all name-lengths in gcc, but that feels so 1970-ish...

**Comment by bsdphk** [comment] 2017-01-30 12:34
Discussed on bugwash.

We will truncate and make private non-SHM allocations in case of collision, with syslog message.

**Comment by drex-knan** [comment] 2017-03-28 14:50
Also affects 4.1.x.

**Comment by freshteapot** [comment] 2017-07-05 10:04
I dont think we should be looking at this problem at the vcl name level.

Yes, we can limit the vcl name to a specific length, but as @gquintard points out the problem is when we concatenate the "vcl name" with a counter, is when it causes the problem. After the vcl name has been happily saved.

My limited knowledge, is part of this problem has a risen when we try to show stats for backends  (via goto vmod) which have long names. As it might be coming across, I am in the camp of avoiding truncating at all costs.

- Consumers of the stats / varnishlog, will need greater knowledge of how our truncating works.
- Saving a vcl name with one name and having it stored as another, will make extra work for 3rd party developers. This can be reduced a little by returning the truncated name when we save a vcl.
- This feels like a short term fix, to a deeper problem that will need tackling. I see the deeper problem as disconnecting the names be it vcl or backends from how we render the data in the logs / stats.

Apologizes if I am way off, as I am unfamiliar with how the ident etc is used internally.

**Comment by Dridi** [comment] 2017-07-05 10:09
This is a workaround for 4.-1plus. If everything goes according to plan 6.0-plus will not have this limitation.

**Comment by Dridi** [comment] 2017-08-30 14:04
Fixed in trunk.

**Closed by Dridi** 2017-08-30 14:04 UTC
Labels: b=bug, c=varnishd, r=5.0, r=trunk

**Comment by fgsch** [comment] 2017-08-30 15:08
Can we have the test added?

**Comment by Dridi** [comment] 2017-08-30 15:20
Done

**Comment by hermunn** [comment] 2017-09-26 09:16
This will not be ported to 4.1
