### ISSUE TITLE
Possibly successful tests hitting the default test timeout

### ISSUE THREAD

**Issue by Dridi** [varnishcache/varnish-cache#2191] opened 2017-01-18 17:27 UTC
Spotted by @nigoroll, visible via vtest, some tests take a handful of seconds and yet hit the 60s timeout and subsequently fail:

```
1 @ SunOS 5.11 i86pc 1.04 64_gcc4.7 uplex

*    top   0.0 TEST ../../../bin/varnishtest/tests/r02035.vtc starting
[...]
*    top   0.0 TEST Streaming range early finish
[...]
**** v1    1.6 vsl|       1003 Timestamp       c Resp: 1484682481.216223 0.000154 0.000042
**** v1    1.6 vsl|       1003 ReqAcct         c 36 0 36 225 5 230
**** v1    1.6 vsl|       1003 End             c
**** v1    1.6 vsl|       1000 SessClose       c REM_CLOSE 1.005
**** v1    1.6 vsl|       1000 End             c
**** v1    1.6 vsl|          0 CLI             - Rd backend.list
**** v1    1.6 vsl|          0 CLI             - Wr 200 168 Backend name                   Admin      Probe                Last updated
vcl1.s1                        probe      Healthy (no probe)   Tue, 17 Jan 2017 19:48:00 GMT
**** v1    1.6 vsl|          0 CLI             - EOF on CLI connection, worker stops
***  v1    2.6 debug| Info: Child (26948) ended\n
***  v1    2.6 debug| Info: Child (26948) said Child dies\n
***  v1    2.6 debug| Debug: Child cleanup complete\n
***  v1    2.6 CLI RX  200
**** v1    2.6 CLI TX| status
***  v1    2.6 CLI RX  200
**** v1    2.6 CLI RX| Child in state stopped
**** v1    2.6 STDOUT poll 0x10
**   v1    2.6 R 26851 Status: 0000 (u 0.216000 s 0.137000)

#     top  TEST ../../../bin/varnishtest/tests/r02035.vtc FAILED (60.004) signal=9

1 @ Fedora 25 x86_64 1.04 dridi

*    top   0.0 TEST ../../../../bin/varnishtest/tests/r02035.vtc starting
[...]
*    top   0.0 TEST Streaming range early finish
[...]
**** v1    1.5 vsl|       1003 ReqAcct         c 36 0 36 225 5 230
**** v1    1.5 vsl|       1003 End             c
**** v1    1.5 vsl|       1000 SessClose       c REM_CLOSE 1.001
**** v1    1.5 vsl|       1000 End             c
**** v1    1.5 vsl|          0 CLI             - Rd backend.list
**** v1    1.5 vsl|          0 CLI             - Wr 200 168 Backend name                   Admin      Probe                Last updated
vcl1.s1                        probe      Healthy (no probe)   Tue, 17 Jan 2017 17:56:54 GMT
**** v1    1.5 vsl|          0 CLI             - EOF on CLI connection, worker stops
***  v1    2.5 debug| Info: Child (17691) ended\n
***  v1    2.5 debug| Info: Child (17691) said Child dies\n
***  v1    2.5 debug| Debug: Child cleanup complete\n
***  v1    2.5 CLI RX  200
**** v1    2.5 CLI TX| status
***  v1    2.5 CLI RX  200
**** v1    2.5 CLI RX| Child in state stopped
**** v1    2.5 STDOUT poll 0x10
**   v1    2.5 R 17653 Status: 0000 (u 0.080904 s 0.041694)

#     top  TEST ../../../../bin/varnishtest/tests/r02035.vtc FAILED (60.085) signal=9
FAIL tests/r02035.vtc (exit status: 2)
```

It could be related to recent changes in `varnishtest`.

Or, it could be the client is hanging because of a streaming bug in that case, I haven't looked beyond vtest.

**Comment by fgsch** [comment] 2017-01-18 22:52
I had a quick look the other day.  Apparently in some cases the conditional variable is missing the broadcast, or at least that's what it looks like.

The difference in output from a working vs a failing test is:

```
**   s1    1.5 === send "B"                                                                                                                        
**** s1    1.5 send| B
```

This was confirmed adding a call to vcl_log() after the pthread_cond_wait() call.

**Comment by bsdphk** [comment] 2017-01-22 08:56
This should be fixed now

**Closed by bsdphk** 2017-01-22 08:56 UTC
Labels: c=varnishtest, r=trunk

**Comment by hermunn** [comment] 2017-01-26 15:42
Backport review: Not applicable to 4.1.
