### ISSUE TITLE
Assert error in BAN_RefBan(), cache/cache_ban.c line 267

### ISSUE THREAD

**Issue by t-h-r-o-w-a-w-a-y** [varnishcache/varnish-cache#2004] opened 2016-07-01 08:22 UTC
Hello there! I'm running varnish-4.1.3-beta1 and randomly getting this panic.

```
Last panic at: Fri, 01 Jul 2016 08:05:00 GMT
"Assert error in BAN_RefBan(), cache/cache_ban.c line 267:
  Condition((b) != 0) not true.
thread = (persistence)
version = varnish-4.1.3-beta1 revision NOGIT
ident = Linux,4.4.0-22-generic,x86_64,-junix,-sdeprecated_persistent,-smalloc,-hcritbit,epoll
Backtrace:
  0x433ba6: varnishd() [0x433ba6]
  0x41790f: varnishd(BAN_RefBan+0x5f) [0x41790f]
  0x463cef: varnishd(smp_load_seg+0x17f) [0x463cef]
  0x4616c5: varnishd() [0x4616c5]
  0x449732: varnishd() [0x449732]
  0x7ff0a1f12184: libpthread.so.0(+0x8184) [0x7ff0a1f12184]
  0x7ff0a1c3f37d: libc.so.6(clone+0x6d) [0x7ff0a1c3f37d]

"
```

After the panic varnish starts to flap and panics constantly with the same assert error. The ban.list gets populated with unknown bans.

```
....[truncated]...
1467354544.743148     4 C
1467354541.100164     4 C
1467354537.544667     2 C
1467354533.877487     1 C
1467354530.401362     2 C
1467354526.900514     1 C
1467354523.452162     3 C
1467354519.942294     6 C
1467354516.373485     6 C
1467354512.846605     4 C
1467354509.350864     3 C
1467354505.846577     7 C
1467354502.230461     7 C
1467354498.757754    10 C
1467354495.548969     2 C
1467354490.869425    10 C
1467354487.146405     1 C
1467354483.659390     8 C
1467354480.769775     5 C
1467354477.527399     2 C
1467354474.038207     8 C
1467354470.447293     6 C
1467354466.843863     2 C
1467354463.319855     2 C
1467354459.865540     1 C
1467354456.403299     3 C
1467354452.932911     0 C
1467354448.607250     6 C
1467354445.147382     5 C
1467354441.770734     3 C
1467354438.456877     6 C
1467354434.857539     4 C
1467354431.527115     4 C
1467354428.167590     3 C
1467354424.646036     4 C
1467354421.341886     4 C
1467354417.978905     5 C
1467354414.699810     5 C
1467354411.269030     3 C
1467354407.828263     7 C
1467354404.461331     7 C
1467354401.078678     5 C
1467354397.889333     0 C
1467354393.378754     6 C
1467354390.013221     6 C
1467354386.849738     8 C
1467354383.650571     1 C
1467354380.404854     2 C
1467351362.212755  4778 C
1467327559.049631 14362 C
1467319739.290791  7088 C
1467315928.664683  3351 C
1467312235.311715  2756 C
1467310100.826486  1622 C
1467303654.883496  4325 C
1467294760.786177 44939 C
1467294023.391572 11287 C
1467293872.929535    11 C
1467293820.521924     6 C
1467293481.720435  2750 C
```
```
DAEMON_OPTS="-a :8080 \
             -T localhost:2000 \
             -f /etc/varnish/persistent.vcl \
             -S /etc/varnish/secret \
             -p thread_pool_min=600 \
             -p thread_pool_max=5000 \
             -s deprecated_persistent,/srv/varnish/persistent/blob_90,90G"
```

Linux,4.4.0-22-generic,x86_64,-junix,-sdeprecated_persistent,-smalloc,-hcritbit
varnish-4.1.3-beta1 revision NOGIT

Thanks!

**Comment by nigoroll** [comment] 2016-07-01 08:29
@lkarsten @mbgrydeland this looks like being fixed with bfb5813ef441c1da6d89603571d34a2edf9bc29c which is not in 4.1
I wonder if maybe we merge all the ban lurker fixes/improvements into 4.1?

**Comment by nigoroll** [comment] 2016-07-01 08:30
@t-h-r-o-w-a-w-a-y consider running master, it should not have this issue

**Comment by olivierHa** [comment] 2016-07-01 19:37
@nigoroll , are thoses fixes of ban lurker scheduled to be included in the 4.1.3-beta3 release ?

**Comment by nigoroll** [comment] 2016-07-01 19:47
@t-h-r-o-w-a-w-a-y  see my first comment. No - or at least now at this point. If you want immediate relieve, build master.

**Comment by lkarsten** [comment] 2016-07-02 22:01
Hi all.

I spent a few hours on Friday reviewing this, and couldn't conclude that Nils' diagnostic was right. If I remember it correctly, I thought that we'd just hit another similar assert later on. Something fundamental was wrong with importing bans from persisted storage. My notes are in the office.

I'll have another look on Monday before deciding on how i'll handle it for 4.1.3.

-Lasse (release manager)

**Comment by nigoroll** [comment] 2016-07-03 09:29
@lkarsten thank you. I stopped thinking about this when I saw that bfb5813 was missing, so if you have a better understanding please share it.

**Comment by lkarsten** [comment] 2016-07-04 09:05
@t-h-r-o-w-a-w-a-y Assuming that this isn't a fresh install, what version did you run before where this was working?

Is the clock on the server stable? Is it running ntpd?

**Comment by t-h-r-o-w-a-w-a-y** [comment] 2016-07-04 09:45
Hi @lkarsten! We were running 4.1.2 with malloc, wasn't enough to our requirements so we switched to persistent storage. 4.1.2 was unstable so we decide to try 4.1.3-beta1, after switching to 4.1.3-beta1 we only notice two different panics, #1995 and this.

Clock is stable (offset ˜ ±0.00800 s) currently running ntpd 4.2.6p5

**Comment by lkarsten** [comment] 2016-07-04 11:02
@t-h-r-o-w-a-w-a-y Hi. Thanks for replying. At this point I'm partial to @nigoroll 's suggestion. I don't think this is a regression introduced in 4.1, but rather something latent from earlier and we should verify and possibly fix it in git master first. Can you try see if you see the same behavior there, please?

Until further information is available, I'm removing this as something that would potentially block 4.1.3 final.

**Comment by t-h-r-o-w-a-w-a-y** [comment] 2016-07-06 11:55
Hello @lkarsten! today we tried with the master branch, varnish instantly panics with the first few requests and is constantly flapping.

```
Panic at: Wed, 06 Jul 2016 11:37:51 GMT
"Assert error in smp_oc_event(), storage/storage_persistent_silo.c line 511:
  Condition(((sg))->magic == (0x45c61895)) not true.
thread = (cache-worker)
version = varnish-trunk revision NOGIT
ident = Linux,4.2.0-36-generic,x86_64,-junix,-sdeprecated_persistent,-smalloc,-hcritbit,epoll
Backtrace:
  0x434696: varnishd() [0x434696]
  0x466d10: varnishd(smp_oc_event+0x1f0) [0x466d10]
  0x4338b5: varnishd(ObjSendEvent+0xb5) [0x4338b5]
  0x42247a: varnishd(EXP_Insert+0x4a) [0x42247a]
  0x42941e: varnishd(HSH_Unbusy+0x15e) [0x42941e]
  0x423445: varnishd() [0x423445]
  0x44b5e1: varnishd() [0x44b5e1]
  0x44ba4b: varnishd() [0x44ba4b]
  0x7fbcff9f3184: libpthread.so.0(+0x8184) [0x7fbcff9f3184]
  0x7fbcff72037d: libc.so.6(clone+0x6d) [0x7fbcff72037d]
busyobj = 0x7fbcfee25020 {
  ws = 0x7fbcfee250a0 {
    id = \"bo\",
    {s, f, r, e} = {0x7fbcfee26f58, +2072, (nil), +57504},
  },
  retries = 5, failed = 0, flags = {do_stream},
  director_req = 0x7fbcfecce940 {
    vcl_name = pix,
    type = round-robin {
    },
  },
  director_resp = 0x7fbcfed2fe78 {
    vcl_name = pix8,
    type = backend {
      display_name = boot.pix8,
      ipv4 = 10.0.1.98,
      port = 8000,
      hosthdr = 10.0.1.98,
      health = healthy,
      admin_health = probe, changed = 1467805065.397329,
      n_conn = 0,
    },
  },
  http[bereq] = 0x7fbcfee25668 {
    ws[bo] = 0x7fbcfee250a0,
    hdrs {
      \"GET\",
      \"/foo/bar/X/1/X/6/X/3/X/30XX6XX8/XXXXXXXXX.orig.jpg\",
      \"HTTP/1.1\",
      \"Accept: */*\",
      \"User-Agent: Mozilla/5.0 (pc-x86_64-linux-gnu) Siege/3.0.5\",
      \"X-Forwarded-For: 10.0.3.47\",
      \"Accept-Encoding: gzip\",
      \"Host: 10.0.1.97\",
      \"X-Varnish: 196612\",
    },
  },
  http[beresp] = 0x7fbcfee25ae0 {
    ws[bo] = 0x7fbcfee250a0,
    hdrs {
      \"HTTP/1.1\",
      \"404\",
      \"Not Found\",
      \"Date: Wed, 06 Jul 2016 11:37:51 GMT\",
      \"Server: Varnish\",
    },
  },
  objcore[fetch] = 0x7fbcf6d3a020 {
    refcnt = 3,
    flags = {},
    exp_flags = {},
    boc = 0x7fbcf6d3c080 {
      refcnt = 2,
      state = req_done,
      vary = (nil),
      stevedore_priv = (nil),
    },
    exp = {1467805071.912304, 0.000000, 0.000000, 0.000000}
    objhead = 0x7fbcf6d3e080,
    stevedore = 0x7fbcfeca6540 (malloc Transient) {
      Simple = 0x7fbcf1cae100
      Obj 0x7fbcf1cb2068 {priv=0x7fbcf1cb2060, ptr=0x7fbcf1cae100, len=200, space=200}
      LEN = 0x0...0
      VXID = 0x00030004
      FLAGS = 0x00
      GZIPBITS = 0x0...0
      LASTMODIFIED = 0x41d5df3b63c00000
      VARY = {len=0, ptr=(nil)}
      HEADERS = {len=0, ptr=0x7fbcf1cae178}
    },
  },
  vcl = {
    busy = 10
    discard = 0,
    state = auto,
    temp = warm,
    conf = {
      srcname = {
        \"/etc/varnish/varnish.vcl\",
        \"Builtin\",
      },
    },
  },
},

"
```

Strange thing, varnish choose as backend 10.0.1.98 but the request hit 10.0.1.97 and the 404. The asset is there and is fetcheable from the varnish server. I notice the same behavior in all the others panics.

**Comment by nigoroll** [comment] 2016-07-11 12:31
@t-h-r-o-w-a-w-a-y would you give eb0b073f77010fd6d85c97d82aa53ed7a5f72b95 or later a try?

**Comment by t-h-r-o-w-a-w-a-y** [comment] 2016-07-21 17:09
thanks! no more issues after trying eb0b073! we are only getting panics related to #1995

**Comment by nigoroll** [comment] 2016-07-23 13:33
@t-h-r-o-w-a-w-a-y thank you, so I'd consider
* the original bug you reported in here fixed by bfb5813
* the additional regression you reported fixed by eb0b073f77010fd6d85c97d82aa53ed7a5f72b95
We still need to look at #1995 tough

**Closed by nigoroll** 2016-07-23 13:33 UTC
Labels: more-info-needed

**Comment by hermunn** [comment] 2016-09-06 14:15
Backport review: Right now I am not seeing myself fixing this in 4.1, as it is not straightforward. If anyone else wants to try, please do, but for now it looks like the fix will be master/5.0 only.

**Comment by lkarsten** [comment] 2016-09-07 08:57
+1 what @hermunn said.

**Comment by nigoroll** [comment] 2016-09-07 09:18
I also agree with @hermunn, I'd either backport (amost?) all of the ban system changes or none, selectively backporting some does not appear sensible to me
