### ISSUE TITLE
Assert error in vwe_thread() after varnish 7.6 upgrade

### ISSUE THREAD

**Issue by DylanoHP** [varnishcache/varnish-cache#4216] opened 2024-10-17 14:25 UTC
### Expected Behavior

Child processes should not die after upgrading to varnish 7.6 as this behaviour was not found in varnish 7.5.
This happens on multiple environments of ours.

### Current Behavior

Child process dies regularly

```
Panic at: Thu, 17 Oct 2024 08:50:46 GMT
Assert error in vwe_thread(), waiter/cache_waiter_epoll.c line 142:
  Condition((vwe->nwaited) != 0) not true.
version = varnish-7.6.0 revision ed1243ca162a7b1d975bc0332f0d66d33f0bc78e, vrt api = 20.0
ident = Linux,5.10.0-32-amd64,x86_64,-jlinux,-smalloc,-sdefault,-hcritbit,epoll
now = 3609344.034919 (mono), 1729155046.842254 (real)
Backtrace:
  0x56171abc1da2: /usr/sbin/varnishd(VBT_format+0x72) [0x56171abc1da2]
  0x56171ab3f82f: /usr/sbin/varnishd(+0x5e82f) [0x56171ab3f82f]
  0x56171abc1318: /usr/sbin/varnishd(VAS_Fail+0x18) [0x56171abc1318]
  0x56171ab9ec89: /usr/sbin/varnishd(+0xbdc89) [0x56171ab9ec89]
  0x7f48133b8ea7: /lib/x86_64-linux-gnu/libpthread.so.0(+0x7ea7) [0x7f48133b8ea7]
  0x7f48132d8acf: /lib/x86_64-linux-gnu/libc.so.6(clone+0x3f) [0x7f48132d8acf]
```

### Context

General production environments where our varnish vcl has been tested numerous amount of times that always worked great, we  now see this behaviour on all machines that got upgraded to varnish 7.6. Child processes dying from time to time.

I don't have great knowledge concerning the varnish ecosystem but in case anything more is needed from my side, feel free to ask and I will provide the necessary information.

### Varnish Cache version

varnishd (varnish-7.6.0 revision ed1243ca162a7b1d975bc0332f0d66d33f0bc78e)

### Operating system

Debian12

**Comment by asadsa92** [comment] 2024-10-17 14:28
Possibly duplicate of https://github.com/varnishcache/varnish-cache/issues/4204

**Comment by nigoroll** [comment] 2024-10-18 10:43
It is a duplicate of https://github.com/varnishcache/varnish-cache/issues/4204

**Closed by nigoroll** 2024-10-18 10:43 UTC
